### ISSUE TITLE
Support lego's dns precheck

### ISSUE THREAD

**Issue by tjhiggins** [vancluever/terraform-provider-acme#102]
Here was the initial issue that added the feature:
https://github.com/go-acme/lego/issues/770

Potential fix for:
https://github.com/vancluever/terraform-provider-acme/issues/87

WrapPreCheck:
https://github.com/go-acme/lego/blob/master/challenge/dns01/precheck.go#L20

This would be a hugely valuable feature to improve consistency. We are generating certs on behalf of multiple users and its important we have a high success rate. 

Using gcloud dns I was getting a failed challenge ~1/10 times.
We switched to cloudflare and its dramatically more reliable only failing ~1/30 times. 

Not a 100% what it should look like, but even being able to add a `sleep 30` would be hugely appreciated.

```tf
resource "acme_certificate" "certificate" {
  #...
  wrap_pre_check = "sleep 30"
  #...
}
```

or even this would be sufficient
```tf
resource "acme_certificate" "certificate" {
  #...
  pre_check_delay = 30
  #...
}
```

**Comment by vancluever** [comment]
@tjhiggins your PR looks sound, just gonna do some general dusting off of the repo before giving it a go. But I don't see a problem with this! More soon.

**Comment by tjhiggins** [comment]
@vancluever sounds good! 

I'd even argue it should be a default since certmanager also does something similar:
https://github.com/jetstack/cert-manager/blob/4f894a7d994e79e2664496f5c9aa82234e4f7aa8/pkg/issuer/acme/dns/dns.go#L122

**Comment by vancluever** [comment]
Hmm, I might skip the default on pre-check - using the acceptance tests as a bar, they don't really fail all that much. TBF Google is the only real provider that I've ever really heard of having consistent problems with this, and as an example, me using R53, I've never had any issues. So I might leave that part out.

**Comment by transferkraM** [comment]
Hey guys, I've very frequent issues with ClouDNS provider being too slow to propagate updates in their infrastructure, which leads to this plugin being unable to generate/refresh certificates in round about 9 of 10 cases. I'd appreciate progress to a configurable pre-dns-validation timeout variable!

**Comment by vancluever** [comment]
This has been added now and will be available in the next release!
