### ISSUE TITLE
Inconsistent behavior within acme_certificate provider specification

### ISSUE THREAD

**Issue by ajohnston9** [vancluever/terraform-provider-acme#105]
### Terraform Version

```
Terraform v0.12.24
+ provider.acme v1.5.0
+ provider.aws v2.57.0
+ provider.random v2.2.1
+ provider.tls v2.1.1
```

### Terraform Configuration Files

```
//main.tf
provider "aws" {
    alias = "aws-dns"
    ...
}

provider "aws" {
    ... // Used for all AWS services *except* DNS
}

module "my_module_with_two_providers" {
    source = "./foo/bar"
    providers {
       aws.dns = aws.aws-dns
       aws.host = aws
   }
}
// ./foo/bar/
provider "aws" {
   alias = "dns"
}
provider "aws" {
   alias = "host"
}
resource "acme_certificate" "cert" {
    ....
   dns_challenge {
      provider = "route53"
      //Does not accept shared credentials file
    }
}
...
```

### Debug Output
N/A

### Crash Output
N/A

### Expected Behavior
Terraform accepts a shared credentials file or allows me to specify a `provider` consistent with other resources. 

### Actual Behavior
Terraform requires specifying the keys separately, meaning a shared credentials file cannot be used and does not allow for providers to be explicitly specified via alias. This goes against guidance in [official documentation ](https://www.terraform.io/docs/configuration/modules.html#providers-within-modules) which states `"it is recommended that they be placed only in the root module of a configuration, since this approach allows users to configure providers just once and re-use them across all descendent modules"` as it forces the child module to become explicitly provider-aware. 

### Steps to Reproduce
1. Configure a specific DNS provider in a root module (see example code above). The root module should pass provider information to the child via the `providers` block using aliases. 
2. Configure a child module that completes an ACME DNS challenge (as above)
3. Note that configuration requires manual specific setting of the access and secret keys, and does not support a shared file or the use of an aliased provider

### Additional Context
N/A

### References
N/A

**Comment by ajohnston9** [comment]
bumping this.

**Comment by vancluever** [comment]
Hey @ajohnston9, this has always been an issue with the ACME provider as mentioned in the [docs for `acme_certificate`](https://www.terraform.io/docs/providers/acme/r/certificate.html#relation-to-terraform-provider-configuration) and the [DNS provider section heading](https://www.terraform.io/docs/providers/acme/dns_providers/index.html#relation-to-terraform-provider-configuration).

Unfortunately this is not necessarily a trivial problem to solve, especially considering lego's own list of DNS providers and DNS provider options grows out of sync with Terraform's. As such I don't anticipate this will be changing any time soon.

Sorry!
