### ISSUE TITLE
Move away from using Terraform TLS provider as a go module

### ISSUE THREAD

**Issue by lazzurs** [vancluever/terraform-provider-acme#114]
Currently this provider uses the TLS provder as a go module which is not supported for Terraform providers.

https://www.terraform.io/docs/extend/best-practices/depending-on-providers.html#do-not-import-providers-as-go-modules

This is also blocking this provider from migrating to the Terraform Plugin SDK.

https://www.terraform.io/docs/extend/plugin-sdk.html

**Comment by vancluever** [comment]
Hey @lazzurs, the TLS provider is only used for testing, it's not actually included in the provider itself.

Not too sure how this is affecting the use of it with the new SDK but if something comes up I'll adjust accordingly. Thanks for bringing it to my attention!
