### ISSUE TITLE
Support certificate provider ACME implementations

### ISSUE THREAD

**Issue by mengesb** [vancluever/terraform-provider-acme#116]
DigiCert happens to support ACMEv2, however the terraform provider requires a registration resource:

https://www.terraform.io/docs/providers/acme/r/registration.html

```hcl
resource acme_registration this {
  ...
}
```

In the case of DigiCert, there's no registration, because the URL is custom and associated with the account... thus registration is not supported:

https://docs.digicert.com/certificate-tools/Certificate-lifecycle-automation-index/acme-user-guide/

This changes the flow of the provider somewhat, however it would mean that the `acme_certificate` resource would no longerr depend on the `account_key_pem` formated output from the `acme_registration` resource.

**Comment by mengesb** [comment]
Skipping the `acme_registration` resource produces the following:

```
Error: acme: error: 400 :: POST :: https://acme.digicert.com/v2/acme/new-account/[[REDACTED]] :: accountDoesNotExist :: No account exists with the provided key, url: 

  on acme.tf line 22, in resource "acme_certificate" "certificate":
  22: resource acme_certificate certificate {
```

**Comment by mengesb** [comment]
Supporting a workflow where the registration can be bypassed much like how the certbot agent can skip registration sounds like a capability the provider should handle

**Comment by vancluever** [comment]
Hey @mengesb, this is interesting... so how are you providing the account key? Just from a local file?

In theory, the registration should _not_ be required as the only thing we're taking from it in `acme_certificate` is the key.

Also, the manual that you linked almost seems to indicate that registration _is_ happening, just without an email address.

Can you maybe confirm with DO and let me know?

**Comment by mengesb** [comment]
@vancluever thanks for dropping in.

Looks like they've changed their documentation once more. So it seems that there are two "keys" that DigCert provides me, but I believe these are both formats that LEGO might not understand - so it may be incompatible. The CLI tool supports providing two flags:

* `--eab-kid` - Key Identifier for External Account Binding (default: None)
* `--eab-hmac-key` - HMAC key for External Account Binding (default: None)

This is displayed from a current certbot using: `certbot -h certonly`

It still requires you to "register unsafely" which I'm unsure if the registration process still occurs or not; or if it's skipped in some way. I know that tthe prior attempts at using the provider resulted in URL calls to `new-account/` that don't work. Got some ideas?

**Comment by mengesb** [comment]
Looking further into go-acme/lego , it seems that `eab` (external account binding` **is** supported, so it looks like I'm the first using this provider to request supporting this method

**Comment by vancluever** [comment]
Hey @mengesb I reviewed https://github.com/go-acme/lego/pull/516 which is where EAB was added into lego. There's nothing specific to `Certifier.Obtain()`, nor are there fields for EAB in [`certificate.ObtainRequest`](https://pkg.go.dev/github.com/go-acme/lego/v4@v4.0.1/certificate#ObtainRequest).

So it looks like EAB is mainly tied to registration which is corroborated by the docs and the certbot options given there.

I'll make the extensions to acme_registration, but unfortunately I'm not going to be able to test it over here as I don't have a DigiCert subscription or account anywhere else that uses EAB. Is this something you'd be OK testing once the PR is available?

**Comment by cpu** [comment]
>  unfortunately I'm not going to be able to test it over here as I don't have a DigiCert subscription or account anywhere else that uses EAB.

One possible idea is to use a local [Pebble](https://github.com/letsencrypt/pebble) instance for this. It [supports EAB](https://github.com/letsencrypt/pebble/pull/288) (_IIRC that's how Lego tested their support too_).

**Comment by vancluever** [comment]
Nice, thanks for that @cpu. I'll definitely have a look at that!

**Comment by mengesb** [comment]
> Hey @mengesb I reviewed [go-acme/lego#516](https://github.com/go-acme/lego/pull/516) which is where EAB was added into lego. There's nothing specific to `Certifier.Obtain()`, nor are there fields for EAB in [`certificate.ObtainRequest`](https://pkg.go.dev/github.com/go-acme/lego/v4@v4.0.1/certificate#ObtainRequest).
> 
> So it looks like EAB is mainly tied to registration which is corroborated by the docs and the certbot options given there.
> 
> I'll make the extensions to `acme_registration`, but unfortunately I'm not going to be able to test it over here as I don't have a DigiCert subscription or account anywhere else that uses EAB. Is this something you'd be OK testing once the PR is available?

Yeah I'm very up to testing this. While I'm not a GOLANG developer, let me know and I'll do what I can. I'm also open to scheduling time if you want to wrangle what you need. Certainly sounds like pebble might be usable too

**Comment by vancluever** [comment]
Yeah I'm definitely going to give pebble a try and see how we do. It might be useful for a lot more than just the EAB test if it all works out. 🙂

**Comment by franta** [comment]
Just for info, https://zerossl.com/documentation/acme/ use EAB. It's free and it can solve out problem with rate limits with let's encrypt. Thanks for working on it.

**Comment by vancluever** [comment]
@mengesb et al, I'm happy to say that this was successfully added and will be in the next version of the provider!

**Comment by mengesb** [comment]
Excellent @vancluever , an update on getting this populated into registry.terraform.io and pulling through the plugin framework of 0.13.x? (RE: #126 )

**Comment by vancluever** [comment]
@mengesb that's being worked on as I type this, so hopefully EOW.

**Comment by iamdeckard** [comment]
@mengesb did you ever get this working for a Private CA with Digicert?

**Comment by mengesb** [comment]
> @mengesb did you ever get this working for a Private CA with Digicert?

Now I don't recall... unfortunately left that company and neglected to follow up here @iamdeckard ; sorry sir! 🙏
