### ISSUE TITLE
Return the DNS records instead of black boxing

### ISSUE THREAD

**Issue by gurre** [vancluever/terraform-provider-acme#117]
I'm having some difficulties using this provider in a multi-account setup. This is normally not a problem when using terraform due to how provider alias works. However due to how Lego requires credentials as arguments for its own AWS client, I'm not sure how I will be able to setup terraform in an agnostic way. The only option seems to use profile credentials?

I would prefer if the DNS records could be returned from the certificate resource, that way it can be set within tf.

**Comment by vancluever** [comment]
Hey @gurre, this sounds like a great idea but I don't have any interest in writing this kind of multi-step challenge resource provider scheme right now. Original proposals for the ACME provider several years ago proposed this kind of setup, but are kind of challenging as DNS challenge records are generally ephemeral and as such break the CRUD nature of how Terraform operates.

Sorry!

**Comment by tomwidmer** [comment]
N.B. This is how the ACM certificate process works - see https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/acm_certificate_validation

I think it works by just leaving the DNS records in there until such time as the terraform resources are destroyed (they don't do much harm, there will only be 1 or 2 per certificate request).

This would allow you to support new DNS services that have their own terraform provider without having to add anything to your provider (and seems a better division of responsibilities)...
