### ISSUE TITLE
ACME Provider not available for Terraform v0.13

### ISSUE THREAD

**Issue by Fred2VOX** [vancluever/terraform-provider-acme#118]
Hi,

The provider ACME is always present in the [documentation](https://www.terraform.io/docs/providers/acme/index.html), but it's not present into the registry. It makes it not available for deployment, even if I apply the proposed upgrade:
`
hashicorp/acme -> terraform-providers/acme
`
Result of terraform apply
`
Failed to instantiate provider "registry.terraform.io/hashicorp/acme" to
obtain schema: unknown provider "registry.terraform.io/hashicorp/acme"
`
Thanks in advance

Fred

**Comment by nyurik** [comment]
I have been using ACME provider with TF 0.13 & 0.13.1 with this code -- seems to be working ok.

```
terraform {
  required_providers {
    acme = {
      source  = "-/acme"
      version = "1.5.0"
    }
...
```

**Comment by vancluever** [comment]
Hey all, this will be addressed in the coming weeks with a new provider release. Watch the repository.

Just closing this now to keep the issue tracker clean.
