### ISSUE TITLE
acme_certificate resource timeout

### ISSUE THREAD

**Issue by ksorn24** [vancluever/terraform-provider-acme#121]
The team is using the ACME provider and during some functional testing we were running into occasional timeouts and we were wondering if there are plans to add the Timeout Stanza capability into the ACME resources mentioned here: https://www.terraform.io/docs/configuration/resources.html#operation-timeouts

I was trying to find where the default timeout and interval is, if someone could point me in the right direction there as well.

Here is a snippet of the timeout occurring during a destroy, which is more than likely due to networking on our end so it would help to be able to adjust timeout as needed (for now we are simply retrying):
```
acme_certificate.certificate: Still destroying... [id=... 10s elapsed]
2020/09/17 15:14:39 [DEBUG] acme_certificate.certificate: apply errored, but we're indicating that via the Error pointer rather than returning it: Post ...acme/revoke-cert: net/http: timeout awaiting response headers
2020/09/17 15:14:39 [ERROR] eval: *terraform.EvalApplyPost, err: Post ...acme/revoke-cert: net/http: timeout awaiting response headers
2020/09/17 15:14:39 [ERROR] eval: *terraform.EvalSequence, err: Post ...acme/revoke-cert: net/http: timeout awaiting response headers
2020/09/17 15:14:39 [ERROR] eval: *terraform.EvalOpFilter, err: Post ...acme/revoke-cert: net/http: timeout awaiting response headers
Error: Post ...acme/revoke-cert: net/http: timeout awaiting response headers
```

**Comment by vancluever** [comment]
Hey @ksorn24, I'm not too sure if adding provider timeout support would address this specific error, at least immediately. This timeout seems to indicate, as you mentioned, deeper network issues (namely a problem receiving a HTTP response). This would require propagation of any timeout settings down the particular HTTP transports, which in this case are probably a part of the lego suite and may not be specifically exposed to the consumer.

Going to close this for now but if this continues to persist for you in the future maybe we can take a look further.
