### ISSUE TITLE
Old tags gone?

### ISSUE THREAD

**Issue by whyman** [vancluever/terraform-provider-acme#122]
Hi,

For example v0.6.0 is missing,

https://github.com/vancluever/terraform-provider-acme/releases/tag/v0.6.0

Also missing seem to be 0.6.0 0.5.0 0.4.0 0.3.0

**Comment by vancluever** [comment]
Hey @whyman, the really old tags you are looking for are probably in https://github.com/vancluever/terraform-provider-acme-old.

This repo is now what was formerly in the terraform-providers org, as it's being moved back to my personal GH in prep for it being ported over to being published to the TF registry as opposed to being part of the default providers set (a process a number of providers are undergoing). This will probably happen over the course of the next few weeks.

Hope this helps!

**Comment by whyman** [comment]
Ah thanks, we have a bunch of scripts that use "this" repo and those versions which started 404iing. Simple enough to update them now we know though.
