### ISSUE TITLE
ACME v1 not found

### ISSUE THREAD

**Issue by djas19** [vancluever/terraform-provider-acme#123]
The documentation links to an older ACMEv1 endpoint that can be used with terraform 11. 

The [link ](https://github.com/vancluever/terraform-provider-acme/releases/tag/v0.6.0)provided in the readme points to release v0.6.0 but this one is nowhere to be found anymore. This linked worked until 10 days ago (18/09/20).

**Comment by vancluever** [comment]
@djas19 thanks for letting me know. The provider has been moved back to my personal user space in preparation for it being published to the Terraform registry, which is probably why this broke. I've updated the readme.

The link you want is: https://github.com/vancluever/terraform-provider-acme-old/releases/tag/v0.6.0

Thanks!
