### ISSUE TITLE
Error: acme: Error -> One or more domains had a problem

### ISSUE THREAD

**Issue by Marvedog** [vancluever/terraform-provider-acme#124]
I receive the following error when using the `acme_certificate` resource. I perform a DNS challenge and the TXT records are successfully created and updated. However, the resource times out, and I cannot seem to find this issue anywhere. 

```shell
Error: acme: Error -> One or more domains had a problem:
[DOMAIN_NAME] time limit exceeded: last error: read udp 127.0.0.1:42897->127.0.0.53:53: i/o timeout
[DOMAIN_NAME] time limit exceeded: last error: read udp 127.0.0.1:60369->127.0.0.53:53: i/o timeout
```

**Comment by vancluever** [comment]
Hey @Marvedog this would imply a DNS timeout on your machine and more than likely not a consequence of the ACME provider. Has this persisted for you?

**Comment by Marvedog** [comment]
Hey! I managed to fix this by increasing the timeout on the CI machine and the `AZURE_PROPAGATION_TIMEOUT`. So it may be the case.

**Comment by vancluever** [comment]
Great! Glad to hear it worked out. 🙂
