### ISSUE TITLE
Issue with Building the Latest Release

### ISSUE THREAD

**Issue by james-crowley** [vancluever/terraform-provider-acme#125]
When building the latest release `v1.5.0` I get the following error:

```
go: golang.org/x/lint@v0.0.0-20190409202823-959b441ac422 used for two different module paths (github.com/golang/lint and golang.org/x/lint)
```

This error seems to be fixed in the latest commit to `master`. 

@vancluever Is there any plan to release a new version, `v1.6.0`, in the near future? Ideally, it would be pulled in upstream by Terraform.

**Comment by vancluever** [comment]
Hey @james-crowley, yeah I've been working on this a bit each week, and just started dusting it off last week. master might not be in the best state right now, but I was able to run tests on it last week just fine. YMMV.

Definitely the intention is to work towards a release once I've done working through the remaining issues in the issue tracker and the outstanding PR.

Thanks!

**Comment by james-crowley** [comment]
@vancluever Thanks for the quick response. Looking forward to seeing a new release.

Any idea on how `v1.5.0` was compiled when there was an error in the release? I am trying to build the provider locally but using the `v1.5.0` release will not work due to the error I stated in my first message.

**Comment by vancluever** [comment]
@james-crowley try `GOFLAGS=-mod=vendor make build`.

The old builds used vendeored dependencies (these have been removed in master but there hasn't been a release yet).
