### ISSUE TITLE
Provider confusion

### ISSUE THREAD

**Issue by mengesb** [vancluever/terraform-provider-acme#126]
With the update to Terraform 0.13, I noticed that this acme provider isn't available via the terraform registry (registry.terraform.io). I did, however, find a fork of your work @vancluever , which gave me pause.

https://github.com/getstackhead/terraform-provider-acme appears to have forked your repo, and is also citing the documentation written in the fork with what looks like no change: https://registry.terraform.io/providers/getstackhead/acme/latest/docs/resources/certificate

Not sure if this is known, however the docs and code and code owner aren't in alignment. I also see some drift, so I'm not sure what's changed

**Comment by vancluever** [comment]
Hey @mengesb, yeah this was brought to my attention last week. It looks like it's been forked and HTTP-01 has been added back in, which I'm not planning on supporting.

Once this provider is fully in the registry I'd imagine the path will be `registry.terraform.io/vancluever/acme` or something like that.

Watch this space!
