### ISSUE TITLE
Akamai (fastdns) : SSL certificate for sub-domains 

### ISSUE THREAD

**Issue by lystopad** [vancluever/terraform-provider-acme#127]
Hi!
Thank you for your code. It is very useful.

I am using Macbook as personal device for testing and Debian GNU/Linux 9 docker container for production-ready deployments.

In both cases I am using terraform 0.13.5 and latest version (1.5.0) of acme terraform provider.

I found that on my Macbook following code works well and can be used to issue SSL Certificate for sub-domain on Akmai (FastDNS/EdgeDNS):

```
variable "subject_alternative_names" {
    default = [ "*.level2.example.com" ]
}

resource "acme_certificate" "certificate" {
    account_key_pem           = acme_registration.reg.account_key_pem
    common_name               = "level2.example.com"
    min_days_remaining        = 30
    key_type                  = "P256"
    subject_alternative_names = length(var.subject_alternative_names) == 0 ? null : var.subject_alternative_names

    dns_challenge {
        provider = "fastdns"
        config = {
            AKAMAI_PROPAGATION_TIMEOUT = 600
        }
    }
}
```

but on Debian GNU/Linux it is failed with following error:

```
Error: error creating certificate: acme: Error -> One or more domains had a problem:
[*.level2.example.com] [*.level2.example.com] acme: error presenting token: 2 errors occurred:
	* fastdns: Zone "level2.example.com" not found.
	* error encountered while presenting token for DNS challenge: fastdns: Zone "level2.example.com" not found.


 [level2.example.com] [level2.example.com] acme: error presenting token: 2 errors occurred:
 	* fastdns: Zone "level2.example.com" not found.
 	* error encountered while presenting token for DNS challenge: fastdns: Zone "level2.example.com" not found.

```

Could you, please, check why it behaves differently and advise how can I fix my deployment.

Thank you!

**Comment by vancluever** [comment]
@lystopad more than likely this is due to some sort of local recursive DNS issue. You can try updating the DNS configuration using the [`recursive_nameservers`](https://registry.terraform.io/providers/vancluever/acme/latest/docs/resources/certificate#recursive_nameservers) argument. Otherwise, check the DNS configuration of your local machine.

Thanks!

**Comment by lystopad** [comment]
Hi, @vancluever !
I will check this idea later.

My yesterday test using most recent version gave me the same results. :(
I was able to create SSL certificate for domain and wildcard-subdomain on my mac, but it failed on jenkins (linux container).

**Comment by vancluever** [comment]
@lystopad thanks for the update! It might be prudent to start tracing the Terraform process or doing some pcaps (tcpdump/wireshark) to see what DNS queries and servers it's hitting, which should give you some good insights into what exactly it's getting tripped up on. That should definitely help you make a decision on what setting to use for `recursive_nameservers`.

Thanks!
