### ISSUE TITLE
How to renew the generated certificate

### ISSUE THREAD

**Issue by Klaitos** [vancluever/terraform-provider-acme#129]
Hello,
I'm using the module to generate a certificate for my route53 subdomain and copying the .pem on the ec2 instance.
I did not found in the doc how to renew automatically the certificate in 90 days once the instance is created with Terraform.

Thanks for the help

**Comment by vancluever** [comment]
Hey @Klaitos, please refer to https://tf-registry.herokuapp.com/providers/vancluever/acme/latest/docs/resources/certificate#certificate-renewal which documents the certificate renewal process.

Thanks!

**Comment by AliRezaBeitari** [comment]
For anyone wondering, here is the updated link: https://registry.terraform.io/providers/vancluever/acme/latest/docs/resources/certificate#certificate-renewal
