### ISSUE TITLE
Expose flag dns01 recursive nameservers only

### ISSUE THREAD

**Issue by xyloman** [vancluever/terraform-provider-acme#130]
There is a requirement that we run terraform provider acme in an air-gapped fashion where access to external DNS servers is not possible.  It appears that cert-manager on k8s has solved this issue by exposing the flag `--dns01-recursive-nameservers-only`.  Is it possible to expose this flag so that only the configured name servers are leveraged and not the name servers associated with the hosted zone.  We are leveraging route 53.

**Comment by xyloman** [comment]
Here is a link to the cert-manager documentation: https://cert-manager.io/docs/configuration/acme/dns01/#setting-nameservers-for-dns01-self-check

**Comment by xyloman** [comment]
Found this issue which appears to be what promoted the additional flag: https://github.com/jetstack/cert-manager/issues/894

We are seeing similar behavior in AWS with Route53 in our environment which blocks outbound external DNS requests.

**Comment by vancluever** [comment]
Hey @xyloman, this was actually exposed last release:

https://registry.terraform.io/providers/vancluever/acme/latest/docs/resources/certificate#disable_complete_propagation

This disables the propagation check that you're referring to. You can disregard the recommendation for testing only; it will work, with the disclaimer that your records may not have propagated to authoritative nameservers by the time the certificate request gets sent to the CA.

**Comment by xyloman** [comment]
@vancluever thanks for the quick reply.  You are correct I was on 1.5.0 bumped to version 1.6.3 and then set the following resource config `disable_complete_propagation  = true` and it appears to be working.
