### ISSUE TITLE
DNS challenge is not using AWS assume role

### ISSUE THREAD

**Issue by Klaitos** [vancluever/terraform-provider-acme#131]
Hello,

I'm using Terraform with AWS provider and an [assume role](https://registry.terraform.io/providers/hashicorp/aws/latest/docs#assume_role) bloc as below : 

```hcl
provider "aws" {
  region  = var.aws_region
  profile = var.aws_profile

  assume_role {
    role_arn     = var.workspace_iam_roles[terraform.workspace]
  }
}
```

```hcl
variable "workspace_iam_roles" {
  default = {
    production = "ARN:MY:PRODUCTION:ROLE"
  }
}
```

This means i have access to an second AWS account on the behalf on my main AWS account where the IAM user is.
This works fine for every ressource created with official Terraform AWS provider.

However, when creating the acme certificate ressource, it seems it does not use the role but try to read/create the route53 DNS challenge on my main AWS account as seen on the error.

```hcl
resource "acme_certificate" "certificate" {
  account_key_pem = acme_registration.reg.account_key_pem
  common_name     = var.hostname

  dns_challenge {
    provider = "route53"
  }
}
```

```hcl
Error: error creating certificate: error: one or more domains had a problem:
[mysubdomain.domain.test] [mysubdomain.domain.test] acme: error presenting token: 2 errors occurred:
        * route53: failed to determine hosted zone ID: AccessDenied: User: MY:ARM:USER is not authorized to perform: route53:ListHostedZonesByName
        status code: 403, request id: d1865fab-34f6-45ae-aef7-7fc2fcf15324
        * error encountered while presenting token for DNS challenge: route53: failed to determine hosted zone ID: AccessDenied: User: MY:ARM:USER is not authorized to perform: route53:ListHostedZonesByName
        status code: 403, request id: d1865fab-34f6-45ae-aef7-7fc2fcf15324
```

Dunno if i'm clear enough ?

The first workaround i've found is to create an IAM user on my second AWS account and give it to acme_certificate resource creation the just to do the DNS challenge..

```hcl
resource "acme_certificate" "certificate" {
  account_key_pem = acme_registration.reg.account_key_pem
  common_name     = var.hostname

  dns_challenge {
    provider = "route53"
    AWS_ACCESS_KEY_ID     = MY_ACCESS_KEY_ON_THE_SUB_ACCOUNT
    AWS_SECRET_ACCESS_KEY = MY_AWS_SECRET_ACCESS_KEY_ON_THE_SUB_ACCOUNT
  }
}
```

Thanks

**Comment by vancluever** [comment]
@Klaitos unfortunately the route53 provider does not have the ability to assume roles like the TF provider does. This would need to be added to the DNS provider on the lego side.

Presently your best bet (and what I actually do to test the provider) is assume the role OOB and just pass the temporary credentials to both Terraform and the route53 DNS provider through the environment, if possible. I use a role helper like [aws-runas](https://github.com/vancluever/aws-runas) to help with this (not a plug, I wrote this several years ago to personally address TF's lack of assume role support at the time 😉 ).

**Comment by Klaitos** [comment]
Thanks for your answer !
