### ISSUE TITLE
do not cleanup _acme-challenge dns record

### ISSUE THREAD

**Issue by MrVJTod** [vancluever/terraform-provider-acme#132]
the dns_challenge code seems to delete the _acme-challenge dns node after the certificate is generated

this is a problem for a few of my zones that have a wildcard dns record *.zone

LE always pulls the resource data for the wildcard, not for the txt record that is actually created

I found that if I inject an innocuous placeholder _acme-challenge into the zone before I run my terraform, the cert is properly generated

I was going to setup aws_dns_zones in my terraform files and import, but they're across several providers, and this is just a hassle as the zones are managed elsewhere
I was going to setup a script to automate this, but still, the zones are across several providers and the scripting is not consistent

I can't seem to find in code where it actually deletes the dns_challenge record to just do something like 'cleanup=persist' or some logic resource property that says "we're not going to delete the DNS leaf node when we're done".

As a "last resort", I might just NS all my wildcard stub zones to a known set of servers where I could do a simple spin through with a script. But, again, this just seems overly complicated if I can instead just tell terraform to not delete the leaf node after processing.

**Comment by vancluever** [comment]
Hey @MrVJTod, you probably won't see this in the code in the provider as this is actually done on the lego side.

At this point in time I'm loathe to add something that bypasses cleanup of DNS challenges as I'm not too sure what the consequence would be to renewals, especially. What I'd suggest to fix the cases where you're seeing this is use the [exec DNS provider](https://registry.terraform.io/providers/vancluever/acme/latest/docs/guides/dns-providers-exec), re-implement the provider functionality in a script, and just no-op cleanup calls.

Thanks!

**Comment by MrVJTod** [comment]
I don't want to persist the DNS challenges, just a blank or empty text record.
Rather than scripts through exec, I'm leaning more toward just importing my zones from neighboring terraform projects with a data reference. I'm just updating my tf build templates to cover all of my cases (route53/cloudflare/google/azure)

**Comment by vancluever** [comment]
@MrVJTod given that DNS challenges are required, this still sounds like an issue best handled by the exec provider, where you can get exactly the behavior you are looking for.
