### ISSUE TITLE
Renewal not working with min_days_remaining = "1"

### ISSUE THREAD

**Issue by philthynz** [vancluever/terraform-provider-acme#134]
**Terraform Versions**
```
Terraform v0.14.3
+ provider registry.terraform.io/hashicorp/azurerm v2.41.0
+ provider registry.terraform.io/hashicorp/random v3.0.0
+ provider registry.terraform.io/hashicorp/tls v3.0.0
+ provider registry.terraform.io/vancluever/acme v2.0.0
```

**Notes**

 - Using a local statelock

-------

I just wanted to test the acme provider to see if the renewals are working. If I use the `acme.sh` client it works as expected with `./acme.sh --issue --dns dns_azure -d test.domain.com --days 1`. I can generate this cert and immediately by running the same command on the same day it will renew it.

However, when using `min_days_remaining = "1"` with the acme provider, running `terraform apply` multiple times does nothing, it says there are no changes to apply. My expectation is for it to have the same behavior as using the `acme.sh` cli.

I also tried to renew the certificate the next day with the same result.

My Terraform code is:

**Module**
```
# ACME registration needs a private key
resource "tls_private_key" "private_key" {
  algorithm = "RSA"
}

# ACME registration
resource "acme_registration" "reg" {
  account_key_pem = tls_private_key.private_key.private_key_pem
  email_address   = "myemail@doamin.com"
}

# Random password for certificate
resource "random_password" "password" {
  length           = 16
  special          = true
  override_special = "_%@"
}

# Generate certificate
resource "acme_certificate" "certificate" {
  account_key_pem           = acme_registration.reg.account_key_pem
  common_name               = var.DOMAIN_NAME
  subject_alternative_names = []
  min_days_remaining        = "1" 
  certificate_p12_password  = random_password.password.result

  dns_challenge {
    provider = "azure"
    config = {
      AZURE_CLIENT_ID       = var.AZURE_CLIENT_ID
      AZURE_CLIENT_SECRET   = var.AZURE_CLIENT_SECRET
      AZURE_ENVIRONMENT     = "public"
      AZURE_SUBSCRIPTION_ID = var.AZURE_SUBSCRIPTION_ID
      AZURE_TENANT_ID       = var.AZURE_TENANT_ID
      AZURE_RESOURCE_GROUP  = var.DNS_RESOURCE_GROUP
    }
  }
}

# Upload certificate to keyvault
resource "azurerm_key_vault_certificate" "certificate" {
  name         = replace(lower(var.DOMAIN_NAME), ".", "")
  key_vault_id = data.azurerm_key_vault.keyvault.id

  certificate {
    contents = acme_certificate.certificate.certificate_p12
    password = random_password.password.result
  }

  certificate_policy {
    issuer_parameters {
      name = "Unknown"
    }

    key_properties {
      exportable = true
      key_size   = 2048
      key_type   = "RSA"
      reuse_key  = false
    }

    secret_properties {
      content_type = "application/x-pkcs12"
    }
  }
}

# Add certificate password as kayvault secret
resource "azurerm_key_vault_secret" "password" {
  name         = "${replace(lower(var.DOMAIN_NAME), ".", "")}-password"
  value        = random_password.password.result
  key_vault_id = data.azurerm_key_vault.keyvault.id
}
```

**Deployment**
```
module "acme" {
  source = "C:/Users/user/Terraform/modules/azurerm/azurerm_acme_lets_encrypt"

  DOMAIN_NAME           = "test.domain.com"
  INIT_RESOURCE_GROUP   = "resource_group"
  DNS_RESOURCE_GROUP    = "dns_resource_group"
  AZURE_CLIENT_ID       = "ID"
  AZURE_CLIENT_SECRET   = "SECRET"
  AZURE_SUBSCRIPTION_ID = "ID"
  AZURE_TENANT_ID       = "ID"
}
```

Is there something I am doing wrong or will `min_days_remaining = "1"` not work for this provider?

**Comment by philthynz** [comment]
It seems the functionality between acme.sh cli and this acme provider is different.

**acmd.sh cli**
`--days <ndays>                    Specifies the days to renew the cert when using '--issue' command. The default value is 60 days.`

**acme provider**
```
min_days_remaining (Optional) - The minimum amount of days remaining on the expiration of a certificate before a renewal is attempted. The default is 30. A value of less than 0 means that the certificate will never be renewed.
```

I have it working by setting `min_days_remaining = "90"`, but it seems kind of misleading compared to the acme.sh cli. I would have thought it would be the same, and `minimum amount of days remaining on the expiration of a certificate before a renewal is attempted` would mean "1" days would be an immediate renewal... Unless I mis understand it 😄

**Comment by vancluever** [comment]
Hey @philthynz, I don't necessarily target feature or UX parity with `acme.sh`, so this is probably not the only divergence you would see, nor do I know if that's purely the case.

In regards to this instance, as you've seen, the definition differs slightly, and if I had to guess how it translates, a setting of `0` in the provider would be the same as a setting of `1` in `acme.sh`. `0` is a valid setting, only negative values disable the check.

Thanks!
