### ISSUE TITLE
Question - Does certificate_p12 include the password for Azure?

### ISSUE THREAD

**Issue by philthynz** [vancluever/terraform-provider-acme#135]
So I have some code to generate a cert and I want to put the cert into an Azure Keyvault.

**Code**
```
# ACME registration needs a private key
resource "tls_private_key" "private_key" {
  algorithm = "RSA"
}

# ACME registration
resource "acme_registration" "reg" {
  account_key_pem = tls_private_key.private_key.private_key_pem
  email_address   = "DLBESITOISCloudServices@education.govt.nz"
  provider        = acme.prod
}

# Random password for certificate
resource "random_password" "password" {
  length           = 16
  special          = true
  override_special = "_%@"
}

# Generate certificate
resource "acme_certificate" "certificate" {
  account_key_pem           = acme_registration.reg.account_key_pem
  common_name               = var.DOMAIN_NAME
  provider                  = acme.prod
  subject_alternative_names = []
  min_days_remaining        = 30
  certificate_p12_password  = random_password.password.result

  dns_challenge {
    provider = "azure"
    config = {
      AZURE_CLIENT_ID       = var.AZURE_CLIENT_ID
      AZURE_CLIENT_SECRET   = var.AZURE_CLIENT_SECRET
      AZURE_ENVIRONMENT     = "public"
      AZURE_SUBSCRIPTION_ID = var.AZURE_SUBSCRIPTION_ID
      AZURE_TENANT_ID       = var.AZURE_TENANT_ID
      AZURE_RESOURCE_GROUP  = var.DNS_RESOURCE_GROUP
    }
  }
}

# Upload certificate to keyvault
resource "azurerm_key_vault_certificate" "certificate" {
  name         = replace(lower(var.DOMAIN_NAME), ".", "")
  key_vault_id = data.azurerm_key_vault.keyvault.id

  certificate {
    contents = acme_certificate.certificate.certificate_p12
    password = acme_certificate.certificate.certificate_p12_password
  }

  certificate_policy {
    issuer_parameters {
      name = "Unknown"
    }

    key_properties {
      exportable = true
      key_size   = 2048
      key_type   = "RSA"
      reuse_key  = false
    }

    secret_properties {
      content_type = "application/x-pkcs12"
    }
  }
}

# Add certificate password as keyvault secret
resource "azurerm_key_vault_secret" "password" {
  name         = "${replace(lower(var.DOMAIN_NAME), ".", "")}-password"
  value        = acme_certificate.certificate.certificate_p12_password
  key_vault_id = data.azurerm_key_vault.keyvault.id
}
```

That all works fine. But when I try to use this certificate in an Azure Application gateway:

```
resource "azurerm_application_gateway" "app_gateway" {

  ssl_certificate {
    name     = var.PUPPET_CERT_NAME
    data     = data.azurerm_key_vault_secret.puppet_cert_data.value
    password = data.azurerm_key_vault_secret.puppet_cert_password_data.value
  }

}
```

I get an error:

```
Original Error: Code="ApplicationGatewaySslCertificatePasswordIncorrect" Message="Password specified for certificate /subscriptions/xxx/sslCertificates/doaminname is incorrect
```

If I don't set a password for the certificate:

```
resource "azurerm_application_gateway" "app_gateway" {

  ssl_certificate {
    name     = var.PUPPET_CERT_NAME
    data     = data.azurerm_key_vault_secret.puppet_cert_data.value
    password = ""
  }

}
```

It works with a blank password.

----

The documentation says if we set `certificate_p12_password`, then `certificate_p12` includes the password. However I don't believe it's working for the PFX certificates, unless I am doing something wrong. Should `certificate_p12` include the password when uploading to a keyvault?

**Comment by philthynz** [comment]
It seems this provider does the job fine. If I export the certificate with `resource "local_file"` the pfx has the password.

The issue is azures confusing way of managing pfx certificates. If you ever import a pfx, it will always ask for the password. Doesn't matter how you import it, via Terraform or UI, into a key vault or directly into the azure resource, and that's it. Kind of simplifies it I guess.

However once the pfx is imported, the password will be stripped. The idea I guess being is that you will need to reference it to connect it to other azure resources.

Reference here: https://docs.microsoft.com/en-us/azure/key-vault/certificates/import-cert-faqs

**Comment by dwaiba** [comment]
I am using the following for passing pfx_b64 to App Gateway v2 with password

`resource "acme_certificate" "tls" {
  account_key_pem          = acme_registration.tls.account_key_pem
  common_name              = var.hostname
  min_days_remaining       = 90
  certificate_p12_password = var.certificate_password

  dns_challenge {
    provider = "azure"
    #https://github.com/vancluever/terraform-provider-acme/blob/master/docs/guides/dns-providers-azure.md
    config = {
      AZURE_CLIENT_ID       = data.azurerm_client_config.current.client_id
      AZURE_CLIENT_SECRET   = var.azurerm_client_secret
      AZURE_RESOURCE_GROUP  = var.dnszone_resourcegroup
      AZURE_SUBSCRIPTION_ID = data.azurerm_client_config.current.subscription_id
      AZURE_TENANT_ID       = data.azurerm_client_config.current.tenant_id
    }
  }
}`


Then


`resource "local_file" "pfx" {
  filename       = "./keys/initial_blank_pkcs12.pfx"
  content        = acme_certificate.tls.certificate_p12
}

output "pfx_b64" {
  description = "The PFX certification in base64."
  value       = filebase64("${local_file.pfx.filename}")
}`

Getting this --

`Failure sending request: StatusCode=0 -- Original Error: Code="ApplicationGatewaySslCertificateInvalidData" Message="Data or Password for certificate 

sslCertificates/tfe-tls-pfx is invalid." Details=[]`

Same with this too
`output "pfx_b64" {
  description = "The PFX certification in base64."
  value       = "${local_file.pfx.filename}"
}`

**Comment by vancluever** [comment]
@dwaiba I don't see any resources pertaining to Azure here (not too sure what those would be unfortunately as I'm not too familiar with Azure). How are you utilizing the output of this resource in Azure and how are you supplying the password used in var.certificate_password to this process?

**Comment by dwaiba** [comment]
Without password.. I understand but it is a bug for Azure

**Comment by vancluever** [comment]
@dwaiba sorry, I'm not quite understanding. Do you mean you are setting a password in `certificate_p12_password` in `acme_certificate`, but are not using it with the password when you provide it to Azure? Or do you mean you are not using a password at all?

If the former, I'd expect you'd need to provide the password to continue. If you mean you're not using a password at all, I'm not too sure if that works, as I don't test in Azure, sorry. You may want to check if you can import the certificate straight into Azure without TF and/or engage Microsoft support on the issue.

**Comment by dwaiba** [comment]
> @dwaiba I don't see any resources pertaining to Azure here (not too sure what those would be unfortunately as I'm not too familiar with Azure). How are you utilizing the output of this resource in Azure and how are you supplying the password used in var.certificate_password to this process?

The outputs of the pls module are used for Public AppGateway

**Comment by vancluever** [comment]
@dwaiba I'm sorry, I don't have experience with the configuration of AppGateway, so I'm not exactly too sure what you'd need to do here. Might be best to engage someone with more experience with this or Microsoft themselves.

**Comment by jdelforno** [comment]
`  ssl_certificate {
    name                = "<domain>"
    key_vault_secret_id = azurerm_key_vault_certificate.primary.secret_id
  }`
  
  
  Reference the key_vault_secret_id and it'll do the rest.
