### ISSUE TITLE
Issues with Azure DNS child zones

### ISSUE THREAD

**Issue by subesokun** [vancluever/terraform-provider-acme#136]
Hi, when trying to get a LE certificate via the DNS challenge on Azure I'm facing an issue when using DNS child zones. My setup looks like the following:

Root DNS Zone `a.com`
  Child DNS Zone `b.a.com`
    Domain to verify `subdomain.b.a.com`

The root DNS zone and child DNS zone are in different subscriptions and hence in a different resource group.

Now, when requesting the certificate I get the following error

```
* azure: dns.ZonesClient#Get: Failure responding to request: StatusCode=404 -- Original Error: autorest/azure: Service returned an error. Status=404 Code="ResourceNotFound" Message="The Resource 'Microsoft.Network/dnszones/a.com' under resource group 'generic' was not found. For more details please go to https://aka.ms/ARMResourceNotFoundFix"
	* error encountered while presenting token for DNS challenge: azure: dns.ZonesClient#Get: Failure responding to request: StatusCode=404 -- Original Error: autorest/azure: Service returned an error. Status=404 Code="ResourceNotFound" Message="The Resource 'Microsoft.Network/dnszones/a.com' under resource group 'generic' was not found. For more details please go to https://aka.ms/ARMResourceNotFoundFix"
```

For some reason the provider doesn't detect that there is a child DNS zone and always uses the root DNS zone. But when setting the subscription and resource group of the root DNS zone I get the following error:

```
Error: error creating certificate: error: one or more domains had a problem:
[subdomain.b.a.com] the server didn't respond to our request
```

I see the TXT record `subdomain.b` for the DNS challenge in my root DNS zone but for some reason the error above gets raised.

Any ideas what I'm doing wrong? If possible I want to use only the child DNS zone to restrict the permission of the service principal to this child DNS zone.

**Comment by vancluever** [comment]
Hey @subesokun, unfortunately we don't really have the means to reproduce issues with most DNS providers, so I can't say for sure. My hunch would be something up with the zone discover mechanism between lego and the DNS provider.

One thing you can do is try reproducing with the lego CLI tool found at https://github.com/go-acme/lego, and submitting an issue in their issue tracker for Azure. If you need to use Terraform and want to work around it, you can also try writing a custom challenge using the [exec](https://registry.terraform.io/providers/vancluever/acme/latest/docs/guides/dns-providers-exec) provider.

Thanks!

**Comment by subesokun** [comment]
Seems like this issue was caused because by a broken DNS zone because Azure had some issues. I've recreated the DNS zone and now it's working (the correct child DNS zone gets used for the DNS challenge)
