### ISSUE TITLE
Alias support

### ISSUE THREAD

**Issue by Kasper-Jensen** [vancluever/terraform-provider-acme#138]
To support modules it would be beneficial to support Alias for the provider.

Let's say one wants a folder structure that goes:
── top layer
    └── descriptive stack of modules
        └── resources
        
One is likely to have the providers at the top layer to avoid potential issues on destroying/redeploying
It would therefore be a very nice feature to support alias, as terraforms other providers does, so that one won't have to break pattern. 

info about multiple provider configuration: [can be found here](https://www.terraform.io/docs/language/providers/configuration.html#alias-multiple-provider-configurations)

**Comment by vancluever** [comment]
@Kasper-Jensen, can you tell me the trouble you are having with using aliases with this provider?

**Comment by Kasper-Jensen** [comment]
I tried to make an example here: https://github.com/Kasper-Jensen/example-acme-provider
Let me know if it does not make sense, then I will try to elaborate further, notice the tagging. v2.0.0 works where as the way of not providing server_url in the lower layers in v3.0.0 does not work. I also provided screenshots that can be seen in main

**Comment by Kasper-Jensen** [comment]
I can try to explain what I want to achieve in another way following a use-case.
The folder structure of the project looks like this:
```
. (top-level)
├── level-1
│   ├── level-2
│   │   └── main.tf
│   └── main.tf
└── main.tf
```
My goal is to configure the ACME provider in main.tf in “top-level” and propagate the provider down to level 2, like this:
```
Top level (location: `./main.tf`):
provider "acme" {
  alias      = "configured-acme-provider"
  server_url = "an endpoint"
}

module "level_1" {
  source = "./level-1"
  providers = {
    acme.configured-acme-provider = acme.configured-acme-provider
  }
}
```
Level 1 (location: `./level-1/main.tf`):
```
provider "acme" { alias = "configured-acme-provider" }
module "level_2" {
  source = "./level-2"
  providers = {
    acme.configured-acme-provider = acme.configured-acme-provider
  }
}
```
Level 2 (location: `./level-1/level-2/main.tf`):
```
provider "acme" { alias = "configured-acme-provider" }
resource "tls_private_key" "private_key" {
  algorithm = "RSA"
}
resource "acme_registration" "reg" {
  provider        = acme.configured-acme-provider
  account_key_pem = "${tls_private_key.private_key.private_key_pem}"
  email_address   = "nobody@example.com"
}
resource "acme_certificate" "certificate" {
  provider                  = acme.configured-acme-provider
  account_key_pem           = "${acme_registration.reg.account_key_pem}"
  common_name               = "www.example.com"
  subject_alternative_names = ["www2.example.com"]
  dns_challenge {
    provider = "route53"
  }
}
```
If we for an example run terraform validate in the top level directory, we receive the following error found here (https://github.com/Kasper-Jensen/example-acme-provider/blob/main/screenshots/v3.0.0.png) as the server_url argument to the ACME is not set. We could provide the server_url argument by passing the value as argument to the underlying modules like so:
```
Top level (location: `./main.tf`):
locals {
  acme_server_url = "an endpoint"
}
provider "acme" {
  alias      = "configured-acme-provider"
  server_url = local.acme_server_url
}
module "level_1" {
  source = "./level-1"
  providers = {
    acme.configured-acme-provider = acme.configured-acme-provider
  }
  acme_server_url = local.server_url
}
# (other resources...)
```
Level 1 (location: `./level-1/main.tf`):
```
variable "acme_server_url" {
  type = string
}
provider "acme" { 
  alias      = "configured-acme-provider"
  server_url = var.acme_server_url 
}
module "level_2" {
  source = "./level-2"
  providers = {
    acme.configured-acme-provider = acme.configured-acme-provider
  }
  acme_server_url = var.acme_server_url
}
# (other resources...)
```
Level 2 (location: `./level-1/level-2/main.tf`):
```
variable "acme_server_url" {
  type = string
}
provider "acme" {
  alias      = "configured-acme-provider"
  server_url = var.acme_server_url 
}
resource "tls_private_key" "private_key" {
  algorithm = "RSA"
}
resource "acme_registration" "reg" {
  provider        = acme.configured-acme-provider
  account_key_pem = "${tls_private_key.private_key.private_key_pem}"
  email_address   = "nobody@example.com"
}
resource "acme_certificate" "certificate" {
  provider                  = acme.configured-acme-provider
  account_key_pem           = "${acme_registration.reg.account_key_pem}"
  common_name               = "www.example.com"
  subject_alternative_names = ["www2.example.com"]
  dns_challenge {
    provider = "route53"
  }
}
```
But this poses some potential issues in Terraform with destroying/redeploying resources.
You also run into the same issue with the AWS provider (as an example), where the region argument is required like server_url for this provider. Here we get around that issue by setting an environment variable (e.g. AWS_DEFAULT_REGION), which the provider uses instead. Perhaps, a solution could be to set the server_url  like that?

**Comment by vancluever** [comment]
@Kasper-Jensen:

This appears to be a bug in Terraform when provider alias names are shared between modules. Can you try renaming the providers for your child modules so that the names do not conflict?

I'd report this issue to Terraform core as well.

Thanks!

**Comment by vancluever** [comment]
@Kasper-Jensen closing this now, feel free to reply if you're still having issues particular to the provider. Thanks!
