### ISSUE TITLE
Connection reset by peer whn accessing acme staging v02 directory

### ISSUE THREAD

**Issue by qpre** [vancluever/terraform-provider-acme#140]
Hello vancity,

Starting yesterday evening (CET) we started getting the following from our production CI on github actions:

```
Error: get directory at 'https://acme-staging-v02.api.letsencrypt.org/directory': Get "https://acme-staging-v02.api.letsencrypt.org/directory": read tcp XX.X.X.XX:61846->XXX.XX.XX.XXX:443: read: connection reset by peer
```

I can't find any related issue anywhere, any idea what might be in motion here ?

Regards

**Comment by KGSvijay** [comment]
Facing the same.Any suggestion?

**Comment by vancluever** [comment]
Hey @qpre, I'm not able to reproduce this. Possibly a transient issue, but nonetheless this is not a kind of issue that we can really look into for you. Sorry!

**Comment by qpre** [comment]
Hey, a little late on my side but thanks for your answer anyway !
