### ISSUE TITLE
NoCredentialProviders: no valid providers in chain on tf 0.13

### ISSUE THREAD

**Issue by FernandoMiguel** [vancluever/terraform-provider-acme#157]
```sh
Terraform v0.13.6
+ provider registry.terraform.io/-/aws v3.29.1
+ provider registry.terraform.io/hashicorp/aws v3.29.1
+ provider registry.terraform.io/hashicorp/null v3.1.0
+ provider registry.terraform.io/hashicorp/random v3.1.0
+ provider registry.terraform.io/hashicorp/template v2.2.0
+ provider registry.terraform.io/hashicorp/tls v3.1.0
+ provider registry.terraform.io/hashicorp/vault v2.18.0
+ provider registry.terraform.io/vancluever/acme v2.1.2
```

```hcl
terraform {
  required_providers {
    acme = {
      source = "vancluever/acme"
    }
    aws = {
      source = "hashicorp/aws"
    }
  }
  required_version = ">= 0.13"
}

provider "acme" {
  server_url = local.acme_server_url
}

resource "tls_private_key" "reg_private_key" {
  algorithm = "RSA"
}

# output "reg_private_key" {
#   value     = tls_private_key.reg_private_key
#   sensitive = true
# }

resource "acme_registration" "reg" {
  account_key_pem = tls_private_key.reg_private_key.private_key_pem
  email_address   = "email@company.com"

  depends_on = [tls_private_key.reg_private_key]
}

output "acme_registration" {
  value     = acme_registration.reg
  sensitive = true
}

resource "tls_private_key" "cert_private_key" {
  algorithm = "RSA"

  depends_on = [tls_private_key.reg_private_key, acme_registration.reg]
}

output "cert_private_key" {
  value     = tls_private_key.cert_private_key
  sensitive = true
}

resource "tls_cert_request" "req" {
  key_algorithm   = "RSA"
  private_key_pem = tls_private_key.cert_private_key.private_key_pem
  dns_names       = var.dns_names

  subject {
    common_name         = var.common_name
    organization        = "company"
    organizational_unit = "cert"
    country             = "USA"
  }
}

output "tls_cert_request" {
  value     = tls_cert_request.req
  sensitive = true
}

resource "acme_certificate" "certificate" {
  account_key_pem         = acme_registration.reg.account_key_pem
  certificate_request_pem = tls_cert_request.req.cert_request_pem

  recursive_nameservers = ["8.8.8.8:53"]

  dns_challenge {
    provider = "route53"
  }

  depends_on = [tls_private_key.reg_private_key, acme_registration.reg]
}

output "acme_certificate" {
  value     = acme_certificate.certificate
  sensitive = true
}
```
```hcl
Acquiring state lock. This may take a few moments...
module.acme.acme_certificate.certificate: Creating...
module.acme.acme_certificate.certificate: Still creating... [10s elapsed]
module.acme.acme_certificate.certificate: Still creating... [20s elapsed]
module.acme.acme_certificate.certificate: Still creating... [30s elapsed]
module.acme.acme_certificate.certificate: Still creating... [40s elapsed]
module.acme.acme_certificate.certificate: Still creating... [50s elapsed]

Error: error creating certificate: error: one or more domains had a problem:
[*.company.com] [*.company.com] acme: error presenting token: 2 errors occurred:
	* route53: failed to determine hosted zone ID: NoCredentialProviders: no valid providers in chain. Deprecated.
	For verbose messaging see aws.Config.CredentialsChainVerboseErrors
	* error encountered while presenting token for DNS challenge: route53: failed to determine hosted zone ID: NoCredentialProviders: no valid providers in chain. Deprecated.
	For verbose messaging see aws.Config.CredentialsChainVerboseErrors
```

we have an acme module that is called by the root module and uses those cert keys into an ASG userdata.
this works fine on terraform 0.12.
once we upgraded to 0.13 it fails on our CI runs with atlantis.
I have been unable to debug further

**Comment by vancluever** [comment]
@FernandoMiguel this looks like an AWS authentication error - I don’t see any in your configuration - you might want to look at https://registry.terraform.io/providers/vancluever/acme/latest/docs/resources/certificate#using-dns-challenges and https://registry.terraform.io/providers/vancluever/acme/latest/docs/guides/dns-providers-route53#argument-reference to see what you need in the resource configuration or the environment for this to work properly. Otherwise, you might want to check your AWS credentials.

I manually test the provider using route53 incidentally using direct environment variables and it was functional on TF 0.14.x earlier this week.

**Comment by FernandoMiguel** [comment]
@vancluever creds are in the root module.
they are ephemeral creds pulled from hashi vault, or an assumed role, depending on the env they run.
does this provider need explicit creds instead of using the aws provider ?

**Comment by vancluever** [comment]
@FernandoMiguel they are different than any specific provider's credentials. See the "Relation to Terraform provider configuration" section (unfortunately the Terraform Registry documentation generator strips the anchors from sub-headings, so I can't direct link, it's farther down in the [Argument Reference](https://registry.terraform.io/providers/vancluever/acme/latest/docs/resources/certificate#argument-reference) section).

**Comment by FernandoMiguel** [comment]
I've added some aws creds as vars.
I'll test tomorrow.
Seems strange to be a breaking change from 0.12 where it was working fine

**Comment by vancluever** [comment]
@FernandoMiguel maybe something up with how TF itself manages provider configuration, or some other shift in your own credential management patterns? This functionality has existed in this form since the provider was initially released ~5 years ago ([and was one of the reasons why it was not initially upstreamed](https://github.com/hashicorp/terraform/pull/7058)).

**Comment by FernandoMiguel** [comment]
Sounds like you went with a lot of trouble to please them..
Thank you for your work on this provider.
