### ISSUE TITLE
Certificate not being recreated after changing server_url to production url

### ISSUE THREAD

**Issue by patrickmarshallcb** [vancluever/terraform-provider-acme#158]
Just recently using this provider to generate tests but after some testing, I've run into an issue related to the server_url configuration.
After changing the server_url from  
server_url  = "https://acme-staging-v02.api.letsencrypt.org/directory" to 
 server_url =  "https://acme-v02.api.letsencrypt.org/directory"

the initially generated cert doesn't get the Issuer updated. Is there anything specific that I need to update to force the server_url request to change for the provided cert?

Thanks.

**Comment by vancluever** [comment]
@patrickmarshallcb please try again with a new [workspace](https://www.terraform.io/docs/language/state/workspaces.html).

The provider does not currently support modification of the CA endpoint within an existing state. Registrations may auto-re-create, but current [issues](https://github.com/vancluever/terraform-provider-acme/issues/88#issuecomment-750700999) surrounding identifying and testing deleted/unknown certificates makes it hard to do the same for them.

Thanks!

**Comment by patrickmarshallcb** [comment]
Thanks for the quick response.
