### ISSUE TITLE
NXDOMAIN for _acme-challenge

### ISSUE THREAD

**Issue by DavyGuedes** [vancluever/terraform-provider-acme#159]
I am unable to create a certificate using this provider,
I have a Linux virtual machine that runs httpd apache serves on port 80.
I can access the application through its domain label provided by azure and also through its external domain (for example: sample.davyguedes.tech).
I have a DNS zone like `davyguedes.tech` and I have a DNS alias record as` sample`.
When I try to run `terraform apply`, the certificate module returns the error `NXDOMAIN for _acme-challenge.sample.davyguedes.tech.`

```hcl
Error: error creating certificate: error: one or more domains had a problem:
[sample.davyguedes.tech] time limit exceeded: last error: NS ns1-05.azure-dns.com. returned NXDOMAIN for _acme-challenge.sample.davyguedes.tech.
```

```hcl
resource "tls_cert_request" "req" {
  key_algorithm   = "RSA"
  private_key_pem = tls_private_key.cert_private_key.private_key_pem
  dns_names       = ["${var.dns_zone_record}.${var.dns_zone}"]

  subject {
    common_name = "${var.dns_zone_record}.${var.dns_zone}"
  }

  depends_on = [
    azurerm_dns_a_record.main,
  ]

}

resource "acme_certificate" "certificate" {
  account_key_pem         = acme_registration.reg.account_key_pem
  certificate_request_pem = tls_cert_request.req.cert_request_pem

  dns_challenge {
    provider = "azure"
    config = {
    // [AZURE config files]
    // [...]
    AZURE_PROPAGATION_TIMEOUT = 300
    }
  }
  depends_on = [
    tls_cert_request.req,
  ]
}
```

**Comment by vancluever** [comment]
@DavyGuedes I cannot look up the NS records for that domain at all (`davyguedes.tech`):

```
$ host -t ns davyguedes.tech
Host davyguedes.tech not found: 3(NXDOMAIN)
```

Additionally, the .tech registry is reporting that the domain does not exist.

```
$ whois davyguedes.tech
...
# whois.nic.tech

The queried object does not exist: DOMAIN NOT FOUND
```

The provider only works with properly registered and internet-reachable domains, unless you are using it in an air-gapped environment where the CA and all DNS servers are all reachable from each other.

Thanks!
