### ISSUE TITLE
Output of the run ? 

### ISSUE THREAD

**Issue by arekgoral** [vancluever/terraform-provider-acme#162]
Hi,

what is the default output of this provider's run ? i.e. where is the certificate placed ?

Do you have some more docs on this?

Cheers

**Comment by arekgoral** [comment]
Ok, scratch that question - found it in here https://registry.terraform.io/providers/vancluever/acme/latest/docs/resources/certificate#attribute-reference

**Comment by vancluever** [comment]
Glad you found it @arekgoral!
