### ISSUE TITLE
OCI Provider Instance Principals

### ISSUE THREAD

**Issue by agregory999** [vancluever/terraform-provider-acme#165]
OCI provider (oraclecloud) -- Can the ACME provider work with Instance Principals? When we run terraform from an OCI instance it is able to run the rest of the OCI components without require OCI_PRIVKEY, OCI_FINGERPRINT, OCI_TENANCY, etc.  This would be nice to have for the Acme provider as well, so that users do not need to have any OCI credentials in their instance where they run terraform from.

https://registry.terraform.io/providers/hashicorp/oci/latest/docs

Thank you.

**Comment by vancluever** [comment]
@agregory999 the `oraclecloud` DNS provider seems to use the OCI SDK, so if there exists some sort of default credential chain in the SDK that will work with the way the [DNS provider is configured in lego](https://github.com/go-acme/lego/blob/master/providers/dns/oraclecloud/oraclecloud.go#L78-L102) then the answer might be yes. You can always try it out with a test environment on the LE staging server!

**Comment by agregory999** [comment]
The instance principal definitely is working for me, as I do not have anything in my provider aside from this:
provider "oci" {
  auth = "InstancePrincipal"
  region = "us-ashburn-1"
}

No matter what, the certificate.tf fails to initialize with this message, so it looks like it blindly requires the config, even if the provider is all set without them:

Error: oraclecloud: some credentials information are missing: OCI_PRIVKEY,OCI_TENANCY_OCID,OCI_USER_OCID,OCI_PUBKEY_FINGERPRINT

Once I uncomment these, I can create certificates properly.

**Comment by vancluever** [comment]
@agregory999 indeed looks like the DNS provider requires those values [here](https://github.com/go-acme/lego/blob/83c626d9a1889fa499bc9c97bc2fdea965307002/providers/dns/oraclecloud/oraclecloud.go#L66-L69) which is probably the source of your issue (see the [`env.Get`](https://github.com/go-acme/lego/blob/83c626d9a1889fa499bc9c97bc2fdea965307002/platform/config/env/env.go#L15-L33) function).

As this is lego-related request, if you'd like to see this changed, I'd recommend putting in an issue with lego. Please see our [documentation for submitting issues to lego](https://github.com/vancluever/terraform-provider-acme/blob/main/docs/lego.md). Additionally, contributions are probably the best way to see your issue resolved quickly.

Thanks!
