### ISSUE TITLE
Cloudflare unrecognized zone when using wildcard zone name.

### ISSUE THREAD

**Issue by ronaldmiranda** [vancluever/terraform-provider-acme#170]
here a simple steps to reproduce:

```lang=HCL
provider "acme" {
  server_url = "https://acme-v02.api.letsencrypt.org/directory"
}

resource "tls_private_key" "private_key" {
  algorithm = "RSA"
  rsa_bits  = 4096
}

resource "acme_registration" "reg" {
  account_key_pem = tls_private_key.private_key.private_key_pem
  email_address   = "r@ronaldmiranda.com.br"
}

resource "acme_certificate" "cert" {
  account_key_pem = acme_registration.reg.account_key_pem
  common_name     = "*.ronaldmiranda.com.br"

  dns_challenge {

    provider = "cloudflare"
    config = {
      CF_API_EMAIL   = var.cloudflare_auth_credentials.email
      CF_API_KEY     = var.cloudflare_auth_credentials.token
      CLOUDFLARE_TTL = 120
    }
  }
}
```

What im receiving trying to apply this code:
```lang=shell
[ronaldmiranda.com.br] [ronaldmiranda.com.br] acme: error presenting token: 2 errors occurred:
	* cloudflare: failed to find zone ronaldmiranda.com.br.: ListZonesContext command failed: HTTP status 400: Invalid request headers (6003)
	* error encountered while presenting token for DNS challenge: cloudflare: failed to find zone ronaldmiranda.com.br.: ListZonesContext command failed: HTTP status 400: Invalid request headers (6003)
```

**Comment by vancluever** [comment]
Hey @ronaldmiranda, this definitely looks like an issue with the lego Cloudflare DNS provider, possibly something that needs updating. Please see our doc on [submitting an issue to lego](https://github.com/vancluever/terraform-provider-acme/blob/main/docs/lego.md) for more details on what you should do to reproduce and put in an issue.

Thanks!

**Comment by Galileo1** [comment]
@ronaldmiranda @vancluever I know this is pretty old issue. But did anyone of you were able to replicate it? I am facing the same issue with cloudflare DNS provider. I have my token with certbot and cloudfare api. They work fine and can list the zones.

**Comment by vancluever** [comment]
@Galileo1 I can't find anything specifically and the provider is up to date with lego. So probably not, but you can ask lego themselves to confirm.

Thanks!

**Comment by Manouchehri** [comment]
@Galileo1 Run with:

```sh
LEGO_DISABLE_CNAME_SUPPORT=true CF_ZONE_API_TOKEN=your_token CF_DNS_API_TOKEN=your_token terraform apply
```
