### ISSUE TITLE
Determine from terraform state whether to block planning during LE outages

### ISSUE THREAD

**Issue by coder543** [vancluever/terraform-provider-acme#177]
Let's Encrypt had a planned outage yesterday that lasted several hours. During this window of time, terraform failed because the ACME module could not reach Let's Encrypt.

I was thinking about this, and it would be awesome if this ACME provider could avoid blocking terraform plans when the LE API returns errors _if_ the terraform plan does not _require_ a new certificate.

I could be completely off base here, but it seems like the ACME provider is storing enough state in Terraform to calculate when the certificates will expire, and so it could avoid throwing errors if we haven't entered the renewal period where LE will actually return a new certificate if the LE API is not functioning. Obviously, if a Terraform plan _requires_ a new certificate -- either through renewal or a completely new certificate request -- then this provider should block Terraform execution.

I'm not sure how easy/hard this would be to implement, but I figured I would share the idea.

**Comment by vancluever** [comment]
@coder543 interesting idea for sure.

Just did a quick memory refresh, and certificates should not need to use the API at all on refresh at all unless certificate data is missing, otherwise it's a no-op.

For registrations/accounts, since they are by nature purely online, there would be no point in refresh without an online check.

I'm curious what the use case is outside of what is described? If it's for addressing issues in resources downstream from the certificate, perhaps moving the certificate to another workspace would be a good idea? By principle, if Terraform could not refresh a resource to get the most up to date state data, it's generally not a good idea to act on the resource, as we can't be sure about whether or not any drift happened. YMMV obviously, but hopefully this makes sense.

**Comment by coder543** [comment]
For more information about the early renewal that I was talking about, [this is the article](https://letsencrypt.org/2021/02/10/200m-certs-24hrs.html) I was thinking of, which references [this proposal](https://mailarchive.ietf.org/arch/msg/acme/b-RddSX8TdGYvO3f9c7Lzg6I2I4/). I guess I was wrong about that proposal being implemented at this point... it looks like I remembered incorrectly.

> Do you have registrations and certificates in the same workspace?

Yes. Is that the wrong thing to do?

**Comment by vancluever** [comment]
Ah, alright, that makes sense then.

Given that this _should_ be the solution, I'm going to close this... but feel free to update the issue if splitting the workspace does not work. 🙂

**Comment by vancluever** [comment]
> Well.. the other question would be: why does the registration portion have to block terraform if you've already registered and the API happens to be down? couldn't the success of that earlier registration be stored in the terraform state?

The refresh process in this case does attempt to fetch registration information from the CA. Currently, it's the account URL only, but that URL is needed for a number of downstream operations, particularly having to do with account updates and certificate issuance, so it's likely important that it is kept up to date (we had an issue with drift in the certificate resource (https://github.com/vancluever/terraform-provider-acme/issues/103), and likely we will need to change the registration resource in a similar way, but we haven't had issues yet).

Given this and other rudimentary functions that refresh serves here (like ensuring that out-of-band deleted accounts are removed from state altogether), I'm of the opinion that there's value in ensuring that we do not proceed in the event of refresh here as to not complicate things to address something that hopefully does not happen too often, and also can be mitigated (by splitting the account off from the certificate and other resources).

Hopefully this makes sense!

PS: I have put the question out internal to see if some of the patterns regarding refresh have changed in the last while, which might change this assessment. I'll follow up if it does. 🙂
