### ISSUE TITLE
Certificate bundle does not contain exactly 2 certificates for Terraform version 0.11.15

### ISSUE THREAD

**Issue by nishantsondhi** [vancluever/terraform-provider-acme#180]
Dear Provider's Developer,

I do notice that with v1.6.0 the support for Terraform 0.11 has been dropped, however there are still folks who are using your awesome provider and using Terraform v 11.x.x. We have started seeing the following error:

"Certificate bundle does not contain exactly 2 certificates" error 

This issue has already been fixed with v2.1.2 for Terraform 0.12 - https://github.com/vancluever/terraform-provider-acme/issues/154.

Can we request for a similar fix be placed for the users who are still using Terraform 0.11 and have started seeing the same issue with v0.11.5 of terraform.

**Comment by vancluever** [comment]
Hey @nishantsondhi, thanks for the kind words! Unfortunately, I don't really have the time to maintain a backport branch/release channel for the plugin. Sorry!

One alternative I could possibly suggest is running a workspace with the most up to date version of TF solely for managing certificates and make those available to other workspaces via [outputs](https://www.terraform.io/docs/language/values/outputs.html).

Hope this helps!
