### ISSUE TITLE
Module Name Mis-Match

### ISSUE THREAD

**Issue by M1kep** [vancluever/terraform-provider-acme#185]
I'd like to preface this with I'm far from well versed in Go, so this may be completely wrong...

While working on updating https://github.com/VladRassokhin/terraform-metadata (Schema Generation for IntelliJ HCL Plugin), I'm running into some issues loading this module. I believe this to be caused by the go.mod file declaring this module as "module github.com/terraform-providers/terraform-provider-acme" instead of "module github.com/vancluever/terraform-provider-acme".

I'm not sure if this is something that can be easily/should be changed.

**Comment by vancluever** [comment]
@M1kep thanks for the callout! Should be fixed now!

**Comment by vancluever** [comment]
PS: Do you need the version bumped? Not too sure if your metadata extractor is version-dependent.

Cheers!
