### ISSUE TITLE
Disable ARM_SUBSCRIPTION_ID inheritance

### ISSUE THREAD

**Issue by philthynz** [vancluever/terraform-provider-acme#187]
Is there a way to disable the inheritance from ARM_SUBSCRIPTION_ID?

This might not be possible, but I am trying to have the Terraform remote statelock in one Azure Subscription, and have this acme provider generate a certificate for a DNS Zone in another Azure Subscription. The issue I can see is that ARM_SUBSCRIPTION_ID is set during a DevOps pipeline task, because it uses a service principal to authenticate with the backend. And this provider set's ARM_SUBSCRIPTION_ID as an alias for AZURE_SUBSCRIPTION_ID and ignores the config block in code.

I am able to do this locally, without a remote backend. But when I want to separate the remote backend and DNS Zone subscriptions, there is an error saying the DNS Zone resource group can't be found when it tries to generate the certificate.

If the code block wasn't ignored and the environment variable not inherited, this would work.

Just wondering if there is a workaround for what I'm trying to achieve?

**Comment by vancluever** [comment]
@philthynz have you just tried zeroing the value out in `config` for the provider?

**Comment by philthynz** [comment]
Yes that won't work unfortunately. Th Azure DevOps Terraform tasks authenticate using a service principal or MSI. The ARM_SUBSCRIPTION_ID variable is set automatically and can't be removed.

I guess either this acme provider needs to have an option to ignore ARM_SUBSCRIPTION_ID, or we will have to have our remote statelock and DNS Zone in the same subscription.

Would it be hard in a future release to have an option that uses the resources config block first before looking at ARM_SUBSCRIPTION_ID?

**Comment by vancluever** [comment]
@philthynz `config` values are actually set as environment variables within the plugin process so that they work properly with lego DNS providers (which take configuration values from the environment). Just curious, did you try it yet? The value would get set for the plugin process only and should not affect the Terraform core binary.

**Comment by philthynz** [comment]
Yes I did try to set AZURE_SUBSCRIPTION_ID to $null in my own environment, but that didn't work because it just took the value from ARM_SUBSCRIPTION_ID.

And I tried to set ARM_SUBSCRIPTION_ID to $null too, and the backend state could not be configured during the INIT.

The only way I was able to get it to work was by using a local statelock, and set ARM_SUBSCRIPTION_ID to $null. Then the config block subscription ID was used and I was able to generate a cert for any DNS Zone in any subscription.

I also tried to set the variable on the cli with `terraform apply -var 'AZURE_SUBSCRIPTION_ID=xxx'`, but it complained that the resource group could not be found.

I also tried to set the subscription is the provider block:

```
provider "azurerm" {
  features {}
  subscription_id = "xxxxxxxxxxxxxxxx"
}
```

And again it complained it could not find the resource group.

It doesn't seem to work as I hoped with a remote state backend and a DNS Zone in a separate subscription. It's not possible to zero out ARM_SUBSCRIPTION_ID because that is needed for the backend remote statelock. Which is a shame but I have worked around it by putting the remote state in the same subscription as the DNS Zone.

**Comment by vancluever** [comment]
@philthynz I'm more referring to the resource configuration itself, like this:

```hcl
resource "acme_certificate" "certificate" {
  ...

  dns_challenge {
    provider = "azure"
    config = {
      ARM_SUBSCRIPTION_ID = ""
    }
  }
}
```

That should zero out the variable within the provider only, not interfering with the rest of Terraform.

**Comment by philthynz** [comment]
Ok, I wasn't aware you could specify it there. It doesn't work If I leave it blank, there is an error in the pipeline `Status=401 Code="InvalidAuthenticationTokenTenant" Message="The access token is from the wrong issuer`.

But, if I specify the subscription ID in that code block:

```
  dns_challenge {
    provider = "azure"
    config = {
      ARM_SUBSCRIPTION_ID   = var.AZURE_SUBSCRIPTION_ID
      AZURE_CLIENT_ID       = var.AZURE_CLIENT_ID
      AZURE_CLIENT_SECRET   = var.AZURE_CLIENT_SECRET
      AZURE_ENVIRONMENT     = "public"
      AZURE_SUBSCRIPTION_ID = var.AZURE_SUBSCRIPTION_ID
      AZURE_TENANT_ID       = var.AZURE_TENANT_ID
      AZURE_RESOURCE_GROUP  = var.DNS_RESOURCE_GROUP
    }
  }
```

It does work.

Thanks for the help!

**Comment by vancluever** [comment]
@philthynz glad it got worked out! 🙂
