### ISSUE TITLE
Use existing Azure context to validate DNS

### ISSUE THREAD

**Issue by cwiederspan** [vancluever/terraform-provider-acme#188]
Forgive me in advance, I'm sure this question has been asked before, but I can't seem to find an answer. 

If I'm creating other Azure resources already - say an App Gateway - is there a way that I can use that same security context to execute the DNS challenge against Azure? In other words, how can I avoid setting the `dns_challenge.config.AZURE_CLIENT_ID` and `AZURE_CLIENT_SECRET` since I've already got an Azure context to work with?

Thanks for any insight.

**Comment by vancluever** [comment]
@cwiederspan aside from `config` in a DNS challenge, you can set these values as environment variables. As long as you can use the same values for both the Azure TF provider as for the Azure ACME DNS provider, you should be good.

The configuration values for the Azure DNS provider are [here](https://registry.terraform.io/providers/vancluever/acme/latest/docs/guides/dns-providers-azure).

Hope this helps!
