### ISSUE TITLE
Empty certificate_p12

### ISSUE THREAD

**Issue by sergiomcalzada** [vancluever/terraform-provider-acme#191]
Hi,

Creating a new acme certificate from the example (properly configured with my own values) set the value of `certificate_p12` to an empty string ([source code](https://github.com/vancluever/terraform-provider-acme/blob/cddbb686003c6b227b8099e88edec5b612d206df/acme/acme_structure.go#L153))

```
resource "tls_private_key" "reg_private_key" {
  algorithm = "RSA"
}

resource "acme_registration" "reg" {
  account_key_pem = tls_private_key.reg_private_key.private_key_pem
  email_address   = var.email_address
}

resource "tls_private_key" "cert_private_key" {
  algorithm = "RSA"
}

resource "tls_cert_request" "req" {
  key_algorithm   = "RSA"
  private_key_pem = tls_private_key.cert_private_key.private_key_pem
  subject {
    common_name = local.common_name
    organization = var.zone.organization
  }
}

resource "random_password" "certificate" {
  length           = 16
  special          = true
}

resource "acme_certificate" "certificate" {
  account_key_pem           = acme_registration.reg.account_key_pem
  certificate_request_pem   = tls_cert_request.req.cert_request_pem
  certificate_p12_password  = random_password.certificate.result
  
  min_days_remaining        = 15

  dns_challenge {
    provider = "azure"
    config = {
      AZURE_TENANT_ID       = var.tenant_id
      AZURE_SUBSCRIPTION_ID = var.subscription_id
      AZURE_RESOURCE_GROUP  = var.zone.rg_name      
    }
  }
}
```

Is there anything else that should be configured?

**Comment by sergiomcalzada** [comment]
Also checked and `acme_certificate.certificate.private_key_pem` is empty

**Comment by vancluever** [comment]
@sergiomcalzada as per the [documentation](https://registry.terraform.io/providers/vancluever/acme/latest/docs/resources/certificate#certificate_p12), `certificate_p12` is not filled in if using an external CSR. You'll have to create your own P12 bundle from your key and certificate data OOB from the resource itself.
