### ISSUE TITLE
Skip revocation when modifying the `subject_alternative_names`

### ISSUE THREAD

**Issue by mboutet** [vancluever/terraform-provider-acme#192]
Updating `subject_alternative_names` will force a new resource to be created which is expected.

However, according to the [code](https://github.com/vancluever/terraform-provider-acme/blob/main/acme/resource_acme_certificate.go#L418), destroying an `acme_certificate` resource will also revoke the certificate.

If the destroy was due to a `terraform destroy`, I think the logic is good. However if the destroy is triggered by one of the property with `ForceNew: true`, I believe it's not ideal because it will cause downtime for services currently using the certificate.

Any thoughts?

**Comment by xynova** [comment]
yep, it would be nice to have a flag to avoid revocations. We are using wildcard certs shared across workloads so we generate and renew the certificates as an independent task from actual deployments. When it comes to renewal, it would be handy for the current certs not to be revoked

https://github.com/vancluever/terraform-provider-acme/blob/main/acme/resource_acme_certificate.go#L430

**Comment by vancluever** [comment]
Hey y'all, give me a few days to think of the implications of this and what the right path forward will be. I was initially thinking that you could probably get around this with `create_before_destroy`, but I'd imagine there would still be issues with the gap between when the certificate is revoked and when the new one can be installed (basically the same problem).

**Comment by mboutet** [comment]
> I was initially thinking that you could probably get around this with create_before_destroy

This would not work in my case because, similar to @xynova, I'm managing a single wildcard certificate for multiple environments. In all cases, revoking the certificate will result in downtime in those environments.

I compiled a local version of this provider without the revocation logic and it works well for my use case.

I think a good solution would be to provide a config flag (either in the `provider` block or `acme_certificate` block or somewhere else) such as `revoke_certiticate_on_destroy` which would be `true` by default.

I can work on a draft PR if this makes sense.

**Comment by vancluever** [comment]
@mboutet:

> This would not work in my case because, similar to @xynova, I'm managing a single wildcard certificate for multiple environments. In all cases, revoking the certificate will result in downtime in those environments.

I understand that, as mentioned in the latter part of that sentence.

If you're going to work on a PR, here are my requests:

* `revoke_certiticate_on_destroy` is configurable at the certificate level, and off by default.
* Please include a test.

Thanks!

**Comment by JordanP** [comment]
@mboutet could you open a PR or just throw in the local code change you have ? I am impacted by this too...

**Comment by mboutet** [comment]
For now, I commented all the code in: 

https://github.com/vancluever/terraform-provider-acme/blob/d75dfac7974519ecde97d71e838cb66207bcf8e9/acme/resource_acme_certificate.go#L419

only keeping the `return null`. I compiled the provider and configured dev override to use the locally compiled one.

**Comment by JordanP** [comment]
Thanks.

@vancluever my golang skill is a bit rusty but the problem is serious imo. Updating the SAN shouldn't revoke the certificate. Any chance you could give a shot at a proper fix in the coming weeks ? :pray:

**Comment by mboutet** [comment]
I agree with @JordanP. Updating the SAN should not under the hood revoke the current certificate. This does not make sense because the existing certificate is most likely in-use on live site(s). If one wants to revoke the old certificate after updating the sites, then they can do it manually.

**Comment by vancluever** [comment]
Hey all, I'll take a stab at getting this out sometime this week (probably later on). Stay tuned!

**Comment by anderius** [comment]
@vancluever Would it be helpful if I provided a PR, with a flag on the certificate resource, named `revoke_certiticate_on_destroy`, that skips the content of `resourceACMECertificateDelete`?

**Comment by vancluever** [comment]
Should be out in 2.7.0, thanks to @anderius for kicking this off! :tada:

**Comment by fredflev** [comment]
Could someone explain why the flag defaults to `true`? 

I could be missing something here but wouldn't it make more sense to default to `false` in order to avoid unwanted revocation and the situation where renewing the certificate via a "delete/create" operation result in a downtime?

**Comment by vancluever** [comment]
@fredflev the skip was only added to delete. You're right; update only renews, it does not revoke. However, if you want to be safe, there's really no repercussions to setting `revoke_certiticate_on_destroy` to `false` to ensure that even re-creation will not revoke your existing certificate.
