### ISSUE TITLE
ACME domain alias mode

### ISSUE THREAD

**Issue by martin-zeug-emp** [vancluever/terraform-provider-acme#196]
It would be great to have the domain alias mode integrated in this provider (for Google DNS)
https://dan.langille.org/2019/02/01/acme-domain-alias-mode/

Greetings,
Martin

**Comment by martin-zeug-emp** [comment]
We found a working solution:
https://github.com/go-acme/lego/blob/8e7bba485fe98dcb6f116eb9f524cd37312540ac/challenge/dns01/dns_challenge.go#L175

LEGO_EXPERIMENTAL_CNAME_SUPPORT=true

**Comment by sphr2k** [comment]
Thanks @martin-zeug-emp - working perfectly.

@vancluever Would it be possible to add a flag for this?

**Comment by vancluever** [comment]
@sphr2k I'm surprised CNAME support is not available within lego other than an experimental feature, but I'm not comfortable with adding a feature that is considered experimental in lego.

I don't really have the cycles to do so, but someone can put in an issue requesting this behavior in lego and it gets merged, we will pick up those changes automatically.

Note that I only did a cursory look, but CNAMEs do not explicitly seem to be a part of RFC8555. However, Let's Encrypt's blog has an article detailing the use of CNAMEs: https://letsencrypt.org/2019/10/09/onboarding-your-customers-with-lets-encrypt-and-acme.html#the-advantages-of-a-cname. This may or may not reflect the opinions of the ISRG however.

Also for more context: https://github.com/go-acme/lego/pull/791
