### ISSUE TITLE
Getting 500 error from Let's Encrypt, left with certificate deleted

### ISSUE THREAD

**Issue by amossc** [vancluever/terraform-provider-acme#201]
We have a cron job which runs once a day to keep a shared wildcard certificate up to date.

Today it deleted the old certificate because it's less than 30 days time to expire, as per the default, but failed to generate the new certificate because of a 500 error on the Let's Encrypt server side.

Here is the log:
```
module.certificates.acme_certificate.certificate["certificate_name"]: Modifying... [id=b016a2a2-726f-d19a-92ed-b37b6c1ae6e4]
module.certificates.aws_acm_certificate.cert["certificate_name"]: Destroying... [id=arn:aws:acm:us-east-1:840818334742:certificate/aa4b25f4-18be-4240-8207-212
495cc3831]
module.certificates.aws_acm_certificate.cert["certificate_name"]: Destruction complete after 0s
module.certificates.acme_certificate.certificate["certificate_name"]: Still modifying... [id=b016a2a2-726f-d19a-92ed-b37b6c1ae6e4, 10s elapsed]

Error: acme: error: 500 :: POST :: https://acme-v02.api.letsencrypt.org/acme/new-order :: urn:ietf:params:acme:error:serverInternal :: Error creating
new order

  on .terraform/modules/.../acme.tf line 14, in resource "acme_certificate" "certificate":
  14: resource "acme_certificate" "certificate" {

```
(redacted a tiny bit to protect the innocent).

The terraform code which failed is:
```
     14 resource "acme_certificate" "certificate" {
     15   for_each = var.certificates
     16
     17   account_key_pem           = acme_registration.reg.account_key_pem
     18   common_name               = each.value["common_name"]
     19   subject_alternative_names = each.value["alternative_names"]
     20   min_days_remaining        = var.min_days_remaining
     21   dns_challenge {
     22     provider = "route53"
     23   }
     24 }
```

What I'd prefer to happen is:
1. Do not delete the old certificate until the new one is created successfully.
2. Retry with some back-off in case of a 500 error from the server.

Is this possible?

**Comment by vancluever** [comment]
@amossc maybe try using [`create_before_destroy`](https://www.terraform.io/docs/language/meta-arguments/lifecycle.html#create_before_destroy) next time and see if that works for you?

Retries would be something that would need to be added on the lego side.

Thanks!
