### ISSUE TITLE
Unclear documentation for dns propagation check

### ISSUE THREAD

**Issue by anderius** [vancluever/terraform-provider-acme#213]
Could we improve the documentation a bit, regarding the `recursive_nameservers` and `disable_complete_propagation`?

As I read the documentation, the system default nameserver OR the nameservers in `recursive_nameservers` will be used to check that the TXT records are propagated.

I did, however, hit my firewall because the provider was trying to check with the authorative nameservers directly, no matter what I configured for `recursive_nameservers`.

Would it be possible to add something about how the authorative nameservers will be checked? If that is indeed the correct behaviour?

The relevant code in lego: https://github.com/go-acme/lego/blob/master/challenge/dns01/precheck.go#L55

**Comment by vancluever** [comment]
@anderius as far as I know, `recursive_nameservers` is for the propagation check for sure.

When you use a config similar to:

```hcl
resource "acme_certificate" "certificate" {
  account_key_pem           = "${acme_registration.reg.account_key_pem}"
  common_name               = "www.${var.domain}"
  subject_alternative_names = ["www2.${var.domain}"]

  recursive_nameservers        = ["8.8.8.8"]
  disable_complete_propagation = true

  dns_challenge {
    ...
  }
}
```

What happens?

PS: We do use `recursive_nameservers` in the tests to ensure that propagation checks _do_ go to the pebble DNS server in CI, versus the system resolver which would not be set to use it.

**Comment by anderius** [comment]
That works, but I only understood that after checking the lego code linked above.

The important part is the word "complete" in "disable_complete_propagation". Maybe we could make it clear in the doc that "complete_propagation" means checking the auhtorative nameservers for the domain? And that a check with system default or "recursive_nameservers", will be done in any case?

I could make an attempt in a PR, maybe easier to discuss.

**Comment by vancluever** [comment]
@anderius feel free to put in a PR! I'll check it after and see what we can do to possibly add context to make sure people fully understand the implications of enabling it.

**Comment by vancluever** [comment]
Hey @anderius, I updated the docs now to address the air-gapped scenario and how the DNS propagation check works in general. This should hopefully clear it up!

The changes will be out in the next release.

**Comment by anderius** [comment]
Sorry, I completely forgot about this.

The documentation you added was very good, thank you!
