### ISSUE TITLE
Is is possible to specify the PEM used to create an acme certificate?

### ISSUE THREAD

**Issue by RacquetMan** [vancluever/terraform-provider-acme#214]
We would like to provide a PEM to acme_certificate to create/renew acme certificates.  Is there anyway to do that or should this be a feature request?

**Comment by vancluever** [comment]
@RacquetMan most inputs to the `acme_certificate` resource take PEM-formatted data. Do you mean certificate requests? See the [Using an External CSR](https://registry.terraform.io/providers/vancluever/acme/latest/docs/resources/certificate#using-an-external-csr) section.
