### ISSUE TITLE
Feature Request: Save the certificate expiration date as a resource attribute

### ISSUE THREAD

**Issue by RickyGrassmuck** [vancluever/terraform-provider-acme#219]
Currently, the certificate expiration date is not able to be determined from within the context of Terraform (ie. operators are unable to determine when the certificate was issued/expires from any Terraform output) and have to either use an external tool such as the `openssl x509` cli tool or by checking in the browser when accessing the site using the cert.

It would be helpful if this information was stored as an attribute for the `acme_certificate` resource so that it could be referenced elsewhere in terraform (ie. outputs). This would also have the added benefit of indicating during a Terraform Plan that a certificate renewal is the reason behind a planned update.

**Comment by citrix-eg** [comment]
Maybe this is helpful for someone in the interim. You cna use the tls_certificate data source to solve this.

data "tls_certificate" "issuer" {
  content = acme_certificate.worker.issuer_pem
}

output "expiry" {
  value = data.tls_certificate.issuer.certificates[0].not_after
}

Build process then inspects outputs and fails.
