### ISSUE TITLE
Support private DNS zones for Azure DNS provider

### ISSUE THREAD

**Issue by knutejoh** [vancluever/terraform-provider-acme#222]
We are setting up an internal ACME provider using smallstep-ca, and we use Azure Private Dns zones for setting up dns. Currently the Azure DNS provider in the acme provider only supports public dns zones, It should be as simple as adding a flag to specify that it's a private dns, and then use /subscriptions/<sub-id>/resourceGroups/<resource-group>/providers/Microsoft.Network/privateDnsZones/
as the url to get the dns zone, and not /subscriptions/<sub-id>/resourceGroups/<resource-group>/providers/Microsoft.Network/dnsZones/

Please add this support.

**Comment by vancluever** [comment]
Hey @knutejoh, as this is requesting a specific feature that is handled by lego, you'd want to make a feature request in that provider. See [this](https://github.com/vancluever/terraform-provider-acme/blob/main/docs/lego.md) page for more details.

Thanks!

**Comment by knutejoh** [comment]
Agree, I'll open a new request when a new Lego version is available supporting this :)
