### ISSUE TITLE
dns_challenge infoblox: View External not found ( WAPI request error: 404('404 Not Found') )

### ISSUE THREAD

**Issue by jdm85nl** [vancluever/terraform-provider-acme#243]
We are experiencing an issue which when using during a acme dns challenge with infoblox.
The dns records where created in infoblox but for some reason it doesn't see the INFOBLOX_VIEW

Error message:

tls_private_key.private_key: Creating...
tls_private_key.private_key: Creation complete after 0s [id=65d63fc203adf3a848627926933d617c9583258b]
acme_registration.reg: Creating...
acme_registration.reg: Creation complete after 0s [id=<acme server>]
acme_certificate.certificate: Creating...
infoblox_ptr_record.lb-kdc: Creating...
infoblox_a_record.lb-kdc: Creating...
infoblox_ptr_record.lb-kdc: Creation complete after 0s [id=record:ptr/ZG5zLmJpbmRfcHRyJC4yMy5hcnBhLmluLWFkZHIuMTAuMjQuOTYuMjIua2Rjb3QtbGdpMDEuYmNwLm1pbmRlZi5ubA:<ip_internal_only>.in-addr.arpa/<internal_only>]
infoblox_a_record.lb-kdc: Creation complete after 0s [id=record:a/ZG5zLmJpbmRfYSQuMjMubmwubWluZGVmLmJjcCxrZGNvdC1sZ2kwMSwxMC4yNC45Ni4yMg:<dnsname_internal_only>/<dnsview_internal_only>]
╷
│ Error: error creating certificate: error: one or more domains had a problem:
│ [<dnsname_internal_only>] [<dnsname_internal_only>] acme: error presenting token: 2 errors occurred:
│  * infoblox: could not create TXT record for <dnsname_internal_only>: WAPI request error: 404('404 Not Found')
│ Contents:
│ { "Error": "AdmConDataNotFoundError: View External not found",
│   "code": "Client.Ibap.Data.NotFound",
│   "text": "View External not found"
│ }
│
│  * error encountered while presenting token for DNS challenge: infoblox: could not create TXT record for <dnsname_internal_only>: WAPI request error: 404('404 Not Found')
│ Contents:
│ { "Error": "AdmConDataNotFoundError: View External not found",
│   "code": "Client.Ibap.Data.NotFound",
│   "text": "View External not found"
│ }
│
│
│
│
│
│   with acme_certificate.certificate,
│   on step0-kdc-cert.tf line 46, in resource "acme_certificate" "certificate":
│   46: resource "acme_certificate" "certificate" {

The code wer are currently using:

# ============================================
# === Create a DNS record via infolbox
# ============================================
# Documentatie: https://registry.terraform.io/providers/infobloxopen/infoblox/latest/docs/resources/infoblox_address_record
# This resource creates a A-Record
#
resource "infoblox_a_record" "lb-kdc" {
  ip_addr   = var.ip_addr
  vm_name   = var.cluster_name
  cidr      = var.cidr
  zone      = var.zone
  dns_view  = "<internal_only>"
  tenant_id = "<internal_only>"
}

# Documentatie: https://registry.terraform.io/providers/infobloxopen/infoblox/latest/docs/resources/infoblox_ptr_record
# This resource creates a PTR-Record
#
resource "infoblox_ptr_record" "lb-kdc" {
  ip_addr   = var.ip_addr
  vm_name   = var.cluster_name
  cidr      = var.cidr
  zone      = var.zone
  dns_view     = "<internal_only>"
  tenant_id    = "<internal_only>"
}

provider "acme" {
  server_url = "<acme server>"
}

resource "tls_private_key" "private_key" {
  algorithm = "RSA"
}

resource "acme_registration" "reg" {
  account_key_pem = "${tls_private_key.private_key.private_key_pem}"
  email_address   = "<internal_only>"
}

resource "acme_certificate" "certificate" {
  account_key_pem           = "${acme_registration.reg.account_key_pem}"
  common_name               = "${var.cluster_name}.${var.zone}"
  #subject_alternative_names = ["${var.cluster_name}.${var.zone}"]

  dns_challenge {
    provider = "infoblox"

    config = {

       INFOBLOX_HOST = var.infoblox_server
       INFOBLOX_USERNAME = var.infoblox_user
       INFOBLOX_PASSWORD = var.infoblox_password
       INFOBLOX_WAPI_VERSION = "2.3.1"
       INFOBLOX_VIEW = "<internal_only>"
       INFOBLOX_SSL_VERIFY = false
    }
  }
}

**Comment by vancluever** [comment]
Hey @jdm85nl, this looks like an issue with the lego DNS provider itself (or your settings with your service provider). As mentioned in the new issue templates, I can't troubleshoot issues with individual providers.

I'd advise reviewing the details at https://github.com/vancluever/terraform-provider-acme/blob/main/docs/lego.md, taking the steps advised there, and submitting an issue with lego if appropriate.

Thanks!
