### ISSUE TITLE
Azure: Save challenge token to Storage Account

### ISSUE THREAD

**Issue by jdelforno** [vancluever/terraform-provider-acme#249]
We're unable to do a DNS challenge atm and we're making use of a storage account to redirect from an App Gateway.

Is there anyway to save the challenge, to the storage account?

**Comment by vancluever** [comment]
Hey @jdelforno, I'm not familiar with Azure, but what you see is what you get in the provider, so I'm going to guess no.

However, you can script a custom DNS challenge with the [exec provider](https://registry.terraform.io/providers/vancluever/acme/latest/docs/guides/dns-providers-exec) or use the http_webroot_challenge (see [Using HTTP and TLS Challenges](https://registry.terraform.io/providers/vancluever/acme/latest/docs/resources/certificate#using-http-and-tls-challenges)) to save the challenge to a directory (note you'd need to mount the path somehow outside of Terraform.

Note that each challenge uses their referenced types (ie: the exec DNS provider still uses DNS-01, and `http_webroot_challenge` uses HTTP-01), so you can't, say, script out an HTTP challenge using the exec DNS provider, which is arguably the more flexible of the two.

Good luck!
