### ISSUE TITLE
Import existing certificates to prevent rate limits

### ISSUE THREAD

**Issue by designermonkey** [vancluever/terraform-provider-acme#263]
I am trying to create a working terraform codebase which has had errors here and there during development. To help in this I have been able to import existing resources to the state using `terraform import` command.

I have just hit a rate limit with the letsencrypt API that I am now blocked from developing on this codebase for 24hrs. I went to the docs to see how to import certificates like with other resource providers, and there is no mention of that functionality.

Would it be possible to add that ability to this provider please?

**Comment by bukowa** [comment]
I run `make cleanup` and then `make apply` and it works for my case, basically controlling targets via Makefile works wonders for me.

````terraform
apply:
	terraform apply --auto-approve --target=acme_registration.reg
	terraform apply --auto-approve --target=digitalocean_droplet.nginx_proxy
	terraform apply --auto-approve

cleanup:
	terraform destroy --auto-approve --target=digitalocean_record.domain
	terraform destroy --auto-approve --target=digitalocean_droplet.nginx_proxy
````

**Comment by vancluever** [comment]
@designermonkey @bukowa I'll mull this and see how I can make it better. In addition to targeted destroys (and probably even better than that), you can set up your certificates in another Terraform workspace and just source the certificates from state with [`terraform_remote_state`](https://www.terraform.io/language/state/remote-state-data).

Also to try and keep yourself from being locked out of production, you can also use the [staging server](https://letsencrypt.org/docs/staging-environment/), which is specifically designed for pre-deployment development.

Thanks!

**Comment by designermonkey** [comment]
Thanks for the input, I realised I had the prod server in use and did a massive facepalm.

**Comment by atrifyllis** [comment]
What I meant by reuse was after a destroy not after a renewal. 
I would expect some kind of account reuse in that case. Why would you recreate account and regenerate cert?
You might argue that production is not recreated so often and you would not hit rate limits. 
But actually using self signed certs from staging causes issues in all envs (e.g. many javascript auth libraries do not allow calling a backend that is behind a self signed cert)

**Comment by vancluever** [comment]
@atrifyllis nothing in the renewal process should not force a new resource (that's why we added updating in the first place through CustomizeDiff several years ago. Can you give me an example of what you mean?

As far as staging goes, I can't really offer anything here, sorry. Staging is specifically the environment Let's Encrypt reserves for folks that need to test their configurations and is designed for that purpose and has better rate limits than production. If you need to test, you can probably check the javascript libraries you use for an "insecure" flag that allows you to skip validation, or add the staging CA certificate in your environment's root store.

**Comment by atrifyllis** [comment]
Thanks for all the feedback! You ask for an example, the use case is pretty clear I think.  I want to reuse a certificate somehow and not regenerate it every t destroy then apply.

**Comment by vancluever** [comment]
@atrifyllis you should not be running `terraform destroy` (or other commands that will similarly destroy a resource) every time you want to renew a certificate. By Terraform convention, destroy is an explicit command to Terraform to tear down infrastructure. The ACME provider interprets that as revoking the certificate. 

You should rather simply let the resource renew naturally through the time controlled by the `min_days_remaining` attribute. You can also force a renew by adjusting this value to a value higher than the time remaining on the certificate.  

[`revoke_certificate_on_destroy`](https://registry.terraform.io/providers/vancluever/acme/latest/docs/resources/certificate#revoke_certificate_on_destroy) was also added relatively recently to allow scenarios where you may not want a certificate to be explicitly revoked on a destroy, you could try setting that to `false`.

Hope that helps!
