### ISSUE TITLE
Version 2.11.X fails Azure provider

### ISSUE THREAD

**Issue by sergiomcalzada** [vancluever/terraform-provider-acme#268]
After upgrading to 2.11.X from 2.10.0 the AzureDNS fails

If I don't provide the name of the DNS_ZONE, the Azure provider detects a default one `t-msedge.net`

```
acme: error presenting token: 2 errors occurred:
* azure: dns.ZonesClient#Get: Failure responding to request: StatusCode=404 -- Original Error: autorest/azure: Service returned an error. Status=404 Code="ResourceNotFound" Message="The Resource 'Microsoft.Network/dnszones/**t-msedge.net**' under resource group 'XXXXXX' was not found. For more details please go to https://aka.ms/ARMResourceNotFoundFix"ç+
```

Also if I set it, it goes an step forward but fails to verify the dns
```
time limit exceeded: last error: NS **ns1.t-msedge.net**. did not return the expected TXT record [
```

**Comment by ldez** [comment]
Do you have a wildcard CNAME?

**Comment by sergiomcalzada** [comment]
We have several certificates generated this way

```
Certificate 0
X.domain.com
*.X.domain.com

Certificate A1
X.domain.com
*.X.domain.com
*.A1.X.domain.com 

Certificate A2
X.domain.com
*.X.domain.com
*.A1.X.domain.com 
*.A2.X.domain.com

Certificate B1
X.domain.com
*.X.domain.com
*.B1.X.domain.com 

Certificate B2
X.domain.com
*.X.domain.com
*.B1.X.domain.com 
*.B2.X.domain.com
```

I have supposed that it should be related to the azure provider/rest-library or to how the "DNS_ZONE_NAME" is detected by this provider or the go-acme

reverting to 2.10 works

**Comment by ldez** [comment]
As explained in the close issue https://github.com/go-acme/lego/issues/1754, your wildcard CNAME is the root of the problem.

You can read the Let's Encrypt explanation about CNAME behavior:
https://letsencrypt.org/2019/10/09/onboarding-your-customers-with-lets-encrypt-and-acme.html#the-advantages-of-a-cname

So you have to create the right CNAMEs for the challenges or set the env var `LEGO_DISABLE_CNAME_SUPPORT` to `true`.

So you can use v2.11.x and close this issue.

**Comment by vancluever** [comment]
Thanks for the assist on this one @ldez!
