### ISSUE TITLE
Consider publishing the provider on the Terraform registry

### ISSUE THREAD

**Issue by moritzheiber** [vancluever/terraform-provider-acme#28]
Since 0.10.6 Terraform [has another way of publishing Terraform providers](https://www.terraform.io/docs/registry/modules/publish.html) different from the usual pattern of being included in the officially distributed list maintained by the terraform-providers organization.

I think one should consider publishing this provider at their public registry because it makes for a way easier and smoother process of publishing and using it.

**Comment by vancluever** [comment]
Hey @moritzheiber, there might be some confusion here as to what the registry is actually for, which is Terraform [modules](https://www.terraform.io/docs/modules/index.html), or re-usable pieces of Terraform code, not [providers](https://www.terraform.io/docs/providers/index.html), which are external binary plugins that support different cloud platforms and other technologies. The ACME plugin hosted here is the latter, of course, and hence can't be pushed to the registry, unfortunately.

The best way for people to locate the provider right now is through the [community providers](https://www.terraform.io/docs/providers/type/community-index.html) page on the TF website, which will lead you to this repository, where releases are published for now.

Thanks!

**Comment by moritzheiber** [comment]
Ah damn, I completely misrepresented (and misunderstood) the intent behind the registry. I'm sorry! Thank you for explaining it thoroughly (and thank you for working on this provider, it's marvelous!)

**Comment by vancluever** [comment]
No problem @moritzheiber, glad to clarify!
