### ISSUE TITLE
[Q] Is new private key created with certificate renewal?

### ISSUE THREAD

**Issue by okruga** [vancluever/terraform-provider-acme#289]
Just want to clarify, since didn't find it in doc.
Will the private key of the certificate be changed after renewal with the acme provider?

thanks.

**Comment by vancluever** [comment]
@okruga it should be kept. We ultimately call [`Renew`](https://github.com/go-acme/lego/blob/2c9f6b19ddfa79bc399389d407985f9bcda7f9b5/certificate/certificates.go#L391-L451) in lego which will use the private key if it exists. We populate the private key [here](https://github.com/vancluever/terraform-provider-acme/blob/4f2c2dc7a5b493e441710d0c30ad404894a41bd8/acme/acme_structure.go#L121-L148) so it exists when `Renew` is called.

Let me know if you run into anything that contradicts this!
