### ISSUE TITLE
Can we have an option to not do domain validation?

### ISSUE THREAD

**Issue by kingcdavid** [vancluever/terraform-provider-acme#306]
Hello

Domain validation isn't always required by CA's, if the CA hierarchy isn't public, or the specific domain has been verified by another method. So is it possible to either remove the restriction of
`dns_challenge,http_challenge,http_memcached_challenge,http_webroot_challenge,tls_challenge` must be specified
and if it they arn't present, don't attempt domain validation
Or have a 'dummy' provider which doesn't try to validate the domain?

Thanks

**Comment by kingcdavid** [comment]
Hi @vancluever 

So, I've actually found an alternative route, so it's not critical at all

The ACME CA is able to use a previous validation of the domains, so it's not so much it doesn't require validation, but they could already be validated, either by a different ACME client or by other means


I actually just used the http_webroot_challenge method, and then the ACME CA is able to detect the domain is already validated

Please feel free to close the issue though


Thanks!

**Comment by vancluever** [comment]
@kingcdavid glad it worked out! We can definitely keep this issue for reference in case it becomes more of a use case. Cheers!

**Comment by on4tux** [comment]
can you reopen this request? We internally use Sectigo via ACME and can skip the challenge. Our current workaround is to use "exec" which runs a simple shell script with "exit 0". Ideally the dns_challenge should indeed have another option "none" to make it permanent.

**Comment by vancluever** [comment]
@on4tux sure. Not too sure when I'll get to it, but I'm happy to have a PR if you want to see it sooner rather than later!

**Comment by joshuaauger** [comment]
@on4tux any more details on your workaround? I'm having a similar issue.

**Comment by vancluever** [comment]
Sorry folks, but I'm closing this again as not planned. I have reviewed the lego code and it doesn't look like there's a good way to support skipping challenges flat out without extra work or workarounds. The internal challenge solver requires that at least one challenge type be registered.

I'm also not going to implement a dummy provider; for those that need such behavior, I'd recommend the workaround posted by @on4tux, which uses the `exec` provider to effectively do the same thing.

Thanks!

**Comment by joshuaauger** [comment]
@vancluever what about supporting all environments variables as regular attributes instead? It would be helpful when we don't have control over the system environment variables.
