### ISSUE TITLE
Azure DNS provider variables map

### ISSUE THREAD

**Issue by jephlu** [vancluever/terraform-provider-acme#317]
Hi @vancluever  

I have an issue on the azure provider, and it seems not directly related to the Lego provider ;)
More a variable mapping issue, i describe it below :) 
Thanks for your help! 

Jean-Philippe

## Context

I am using terraform-provider-acme module with DNS provider on azure.

I found that the following settings in the config section cannot be used:

- "AZURE_CLIENT_ID"
- "AZURE_CLIENT_SECRET"
- "AZURE_RESOURCE_GROUP"
- "AZURE_SUBSCRIPTION_ID"
- "AZURE_TENANT_ID"

_**IF**_ the ARM_* variables are set, respectively:

- "ARM_CLIENT_ID"
- "ARM_CLIENT_SECRET"
- "ARM_RESOURCE_GROUP"
- "ARM_SUBSCRIPTION_ID"
- "ARM_TENANT_ID"

## Possible solution
Map an ARM_* variable only if its equivalent AZURE_* variable does not exist in the config section.

This seems to be achieved in this part of the code in: https://github.com/vancluever/terraform-provider-acme/blob/main/acme/dnsplugin/dns_provider_factory.go

```
"azure": func() (challenge.Provider, error) {
		mapEnvironmentVariableValues(map[string]string{
			"ARM_CLIENT_ID":       "AZURE_CLIENT_ID",
			"ARM_CLIENT_SECRET":   "AZURE_CLIENT_SECRET",
			"ARM_RESOURCE_GROUP":  "AZURE_RESOURCE_GROUP",
			"ARM_SUBSCRIPTION_ID": "AZURE_SUBSCRIPTION_ID",
			"ARM_TENANT_ID":       "AZURE_TENANT_ID",
		})
		p, err := azure.NewDNSProvider()
		if err != nil {
			return nil, err
		}
```

Note : it is the only DNS provider that has this mapping system in the file.

## My use case

Deployment of infrastructure in terraform in a "Lab" subscription (with the AzureRM provider).
My Azure DNS zone is in another "Shared" subscription.

Today, as a workaround, I have to play with the ARM_SUBSCRIPTION_ID variable: ${{ secrets.AZ_SUB_ID_SHARED }}
(yml workflow in gitHub action) for the terraform-provider-acme module to inherit and find the DNS zone.

In parallel, for my AzureRM deployments to be done well on the "Lab" Sub, I must override the configuration of the AzureRM provider:

```
provider "azurerm" {
   features {}
   subscription_id = "${var.AZ_SUB_ID_LAB}"
}
```

**Comment by vancluever** [comment]
Hey @jephlu, these exceptions were added in https://github.com/vancluever/terraform-provider-acme/commit/83762aed136b771c65bfcf6bb8eb23791daf4aa8 to allow continuity with the TF Azure provider.

If you need to specify different settings for your DNS than the one you use for the Azure provider in TF, is just using the `ARM_` equivalents in config not working? This would be the best solution.

**Comment by jephlu** [comment]
The ARM_SUBSCRIPTION_ID is set with my terraform provider. 

I specify : 

```
config = {
        AZURE_SUBSCRIPTION_ID = "<sub_id_for_dns_zone>" 
    } 
```

"AZURE_SUBSCRIPTION_ID" in the config section does not take the precedence on ARM_SUBSCRIPTION_ID.

**Comment by vancluever** [comment]
@jephlu what I'm saying is change that to:

```
config = {
        ARM_SUBSCRIPTION_ID = "<sub_id_for_dns_zone>" 
    }
```

And then the explicit setting should be used without being overridden.

**Comment by jephlu** [comment]
hello @vancluever ,
I tested it and you're right, it works fine. 👍 
Did not think about override the var itself, I stuck to the documentation !
Thanks for your help and your work on the module!
