### ISSUE TITLE
Support Timeout configuration options

### ISSUE THREAD

**Issue by berney** [vancluever/terraform-provider-acme#32]
I'm also hitting #30 Error 409 - urn:acme:error:malformed - Certificate already revoked which seems to occur after a destroy has timed out after 3 minutes. I'm consistently hitting this. As well as fixing #30 can you add support for configurable timeouts https://www.terraform.io/docs/configuration/resources.html#timeouts

**Comment by EricMCornelius** [comment]
Hitting this every time I make an update as well.  Using the aws route53 dns configuration.

After re-running the cert seems to have been revoked, so #30 then triggers.

**Comment by vancluever** [comment]
Hey all, I've implemented the `delete` timeout for revocation, although I've set the default at 20 minutes (increasing it from 3), so hopefully you never have to set it. :) 

This should be fixed in the next release. Thanks!

**Comment by vancluever** [comment]
PS: I've been doing some thinking about this as well around actually just dropping post-revocation OCSP checks completely. This used to work great around when I first wrote the provider, but more often than not now it just causes problems.

There is also much musing about the [general unreliability of revocation infrastructure](https://medium.com/@alexeysamoshkin/how-ssl-certificate-revocation-is-broken-in-practice-af3b63b9cb3).

This will probably be what we do for 1.0.0, while we do some other housekeeping. At best it will be optional.
