### ISSUE TITLE
Adding HTTP (s3) Verification

### ISSUE THREAD

**Issue by kingcdavid** [vancluever/terraform-provider-acme#327]
Do we think we could add in HTTP verification methods to the module for configs which can't use DNS

The scenario i'm thinking is an s3 bucket,
You would have to have the s3 bucket already created, and the domain pointing to it and http(s) enabled

then it would be the s3 plugin's responsibility to just upload the TXT validation code to .well-known/acme-challenge/<TOKEN> in the s3 bucket and then request HTTP/HTTPS validation instead of DNS?

Would be interested to try it out if we would be happy with the approach?

**Comment by vancluever** [comment]
@kingcdavid that sounds interesting, sounds like it would work like the memcached challenge (see [using HTTP and TLS challenges](https://registry.terraform.io/providers/vancluever/acme/latest/docs/resources/certificate#using-http-and-tls-challenges)) which we currently support.

Like the memcached challenge it would be nice if this was included in lego proper.

Is this what you were thinking?

**Comment by kingcdavid** [comment]
So i hadn't considered the upstream requirements, but have made issue and PR into the lego repo now, so hopefully can use that when released

**Comment by kingcdavid** [comment]
Hey, just working on the PR now, the implementation is looking OK, but could you advise on testing?

with s3 being a cloud service, it's tricky to mock, what would you advise?

**Comment by vancluever** [comment]
@kingcdavid glad to hear it's going well!

If cloud cost is an issue (and/or you'd want a version that can run in CI) then possibly look at [LocalStack's S3 implementation](https://docs.localstack.cloud/user-guide/aws/s3/).

**Comment by kingcdavid** [comment]
Adding PR here
https://github.com/vancluever/terraform-provider-acme/pull/330

**Comment by kingcdavid** [comment]
didn't mean to close!

**Comment by vancluever** [comment]
@kingcdavid this is now merged and should be out soon with 2.17.0!
