### ISSUE TITLE
acme: error: 403 :: POST : An account with the provided public key exists but is deactivated

### ISSUE THREAD

**Issue by samymokhtari** [vancluever/terraform-provider-acme#332]
Hi, i'm getting an error when I try to apply my terraform. It throws me the following error : 
![image](https://github.com/vancluever/terraform-provider-acme/assets/37446507/db836991-cacf-4073-a8cb-05dc5072e2b4)

I have seen the closed issues that refer to this problem but no one solution worked for me .. I removed my state on my both tls_private_key (one for stage, other for prod). Also I've runned my apply with the argument -replace to regenerate my keys but still same problem.

I don't know what to do anymore to resolve this, can you help me ?

Our infrastructure is currently runnin on Azure and here is the code (I suppose this error happens bc the registration has been revoked so the account has been disabled) : 

```
resource "tls_private_key" "noprod" {
  algorithm = "RSA"
}

resource "acme_registration" "noprod" {
  account_key_pem = tls_private_key.noprod.private_key_pem
  email_address   = var.certificate_admin_email
}

resource "acme_certificate" "noprod" {
  account_key_pem = acme_registration.noprod.account_key_pem
  common_name     = "*.${var.landing_zone_public_dns_zone.name}"
  key_type        = 2048

  ...
  }
}
```

**Comment by samymokhtari** [comment]
I've ran the terraform without any ssl configuration and the tls private key was successfully regenerated 

Notice that I forced the regeneration by adding : 
```
resource "tls_private_key" "noprod" {
  algorithm = "RSA"
  rsa_bits = 4096
}

```

**Comment by vancluever** [comment]
@samymokhtari glad you figured it out! I'm curious as to why tainting the `tls_private_key` resource didn't force the resource as `account_key_pem` in `acme_registration` as that field is set to ForceNew, but glad you figured it out!

Just to clarify, when you did taint the resource, did a future plan show that the `tls_private_key` resource was going to be re-created at least?
