### ISSUE TITLE
Generating Certificates works on 2.15.1 (acme-certificate) but not anymore on 2.17

### ISSUE THREAD

**Issue by hderudder** [vancluever/terraform-provider-acme#337]
When generating certificates with acme-certificate in Terraform I can do that successfully with 2.15.1 (using route53 challenge), but with exactly the same templates and content, it doesn't work anymore on 2.17. Running a Terraform plan doesn't show anomalies, but when running the apply I consistently get errors like the ones below:

[5iemlrww.vncloud-staging.synamedia.com] [5iemlrww.vncloud-staging.synamedia.com] acme: error presenting token: 2 errors occurred:
* rpc error: code = Unknown desc = route53: failed to determine hosted zone ID: operation error Route 53: ListHostedZonesByName, failed to resolve service endpoint, an AWS region is required, but was not found

Do note that that zone really exists, and does respond properly to challenges, so that is not the issue. It is a know zone in route53, and it has a valid zone ID.

I do not know how much more info you need from me in order to be able to troubleshoot/investigate this further, so please do call out. I reverted back to 2.15.1 for now.

**Comment by vancluever** [comment]
@hderudder the error message seems to indicate that a region is required. Are you supplying one with `AWS_REGION` or equivalent?

The AWS Go SDK was recently changed in lego to v2 which may have affected the client chain and what is explicitly required for settings.

**Comment by hderudder** [comment]
I am providing a region, yes. But if zone ID's for FQDN's need to be retrieved from AWS, the region is always us-east-1 because Route53 is a global service, so it's kind of decoupled of the region I am deploying my resources really in. So, I would be surprised that is the issue.

**Comment by vancluever** [comment]
@hderudder even if route53 is a global service, maybe it’s still using regional API endpoints. I’m not too sure, but that’s what the error message seems to indicate.

[This](https://github.com/go-acme/lego/blob/6af2c756ac73a9cb401621afca722d0f4112b1b8/providers/dns/route53/route53.go#L294) seems to be the only reference in the provider to `ListHostedZonesByName`, which is pretty straightforward. Additionally, I just tested the route53 provider last night with no additional settings (so full auto-discovery), and everything was fine.

**Comment by Narakuku** [comment]
I encountered the same problem with Route 53 with vancluever/acme 2.17.0

Nonetheless, setting AWS_DEFAULT_REGION as an environment variable resolved the issue.

`export AWS_DEFAULT_REGION=eu-north-1
`

Despite specifying a region in Terraform, I'm unsure why this no longer corresponds to "AWS_DEFAULT_REGION" and I had to set it manually.
```
provider "aws" {
  region = "eu-north-1"
}
```

**Comment by vancluever** [comment]
@Narakuku see https://registry.terraform.io/providers/vancluever/acme/latest/docs/resources/certificate#relation-to-terraform-provider-configuration. Our configuration and the AWS provider are not one and the same.

WRT fixing this actual issue, this looks like a wontfix for the time being. Rolling back the AWS provider version is pretty much impossible, and given that this is the only change, that's the only cause I can see here unless some new development emerges. Additionally, setting  the region to a hard value here does not seem to be the correct path forward here.

My recommendation is definitely to make sure `AWS_REGION` or `AWS_DEFAULT_REGION` is set when making requests, or that it's set in some other way in the credential chain (e.g. AWS configuration files).
