### ISSUE TITLE
Terraform Provider Timing Out, No Option to Change the Timeout Value

### ISSUE THREAD

**Issue by lyntux** [vancluever/terraform-provider-acme#347]
In reference to a closed issue, "acme_certificate resource timeout" #121, I am running into timeout issues as well.

The issue I am having is that when I run this Terraform provider I get a timeout after 30 seconds. I can look at the CA records and see that the certificate does get submitted and signed, but it can take 1-2 minutes before the cert is signed. The cert doesn't get delivered back to the Terraform provider because it's already timed out.

I can reproduce the issue with the `lego` tool.

```
> lego -s $url -d $domain -m $email --accept-tos \
    --eab --kid $kid --hmac $hmac \
    --http --http.webroot $output run

2023/09/18 08:47:08 [INFO] [redacted] acme: Obtaining bundled SAN certificate
2023/09/18 08:47:09 [INFO] [redacted] AuthURL: https://redacted/authorization/redacted
2023/09/18 08:47:09 [INFO] [redacted] acme: authorization already valid; skipping challenge
2023/09/18 08:47:09 [INFO] [redacted] acme: Validations succeeded; requesting certificates
2023/09/18 08:47:10 [INFO] Wait for certificate [timeout: 30s, interval: 500ms]
2023/09/18 08:47:40 Could not obtain certificates:
        error: one or more domains had a problem:
[redacted] time limit exceeded: last error: %!w(<nil>)
```

In `lego`, the `--cert.timeout` value defaults to 30 seconds. When I add that flag (on the third line in my example) I get a certificate issued successfully.

```
> lego -s $url -d $domain -m $email --accept-tos \
    --eab --kid $kid --hmac $hmac \
    --cert.timeout 120 \
    --http --http.webroot $output run

2023/09/18 08:59:01 [INFO] [redacted] acme: Obtaining bundled SAN certificate
2023/09/18 08:59:02 [INFO] [redacted] AuthURL: https://redacted/authorization/redacted
2023/09/18 08:59:02 [INFO] [redacted] acme: authorization already valid; skipping challenge
2023/09/18 08:59:02 [INFO] [redacted] acme: Validations succeeded; requesting certificates
2023/09/18 08:59:02 [INFO] Wait for certificate [timeout: 2m0s, interval: 2s]
2023/09/18 08:59:54 [INFO] [redacted] Server responded with a certificate.
```

As far as I can tell, this `--cert.timeout` option isn't available via the Terraform provider. Would it would be possible to add that as an option?

**Comment by vancluever** [comment]
Hey @lyntux I think we can add this! Stay tuned, hopefully I can have this done sometime this week.

Cheers!

**Comment by vancluever** [comment]
@lyntux this is now implemented in v2.18.0! It should be out shortly.

Thanks!

**Comment by lyntux** [comment]
Works perfectly! Thanks!

```
acme_certificate.certificate: Creating...
acme_certificate.certificate: Still creating... [10s elapsed]
acme_certificate.certificate: Still creating... [20s elapsed]
acme_certificate.certificate: Still creating... [30s elapsed]
acme_certificate.certificate: Creation complete after 34s
```

That would have timed out before.

**Comment by vancluever** [comment]
@lyntux awesome! Glad it's working for you now 😀
