### ISSUE TITLE
unable to force authentication method using `azuredns` challenge provider

### ISSUE THREAD

**Issue by sdib** [vancluever/terraform-provider-acme#360]
Hello,

I'm using a self hosted GitHub runner hosted on Azure Container Instance with a MSI enabled to apply my terraform.
The runner doesn't have any AZURE_* environment variable defined.
I'm using [OIDC authentication](https://docs.github.com/en/actions/deployment/security-hardening-your-deployments/configuring-openid-connect-in-azure)
I'm using `acme_certificate` with the `azuredns` provider for DNS challenge (acme TF provider version 2.18.0) : 
```terraform
resource "acme_certificate" "this" {
  account_key_pem    = acme_registration.this.account_key_pem
  common_name        = local.hostname
  min_days_remaining = 30
  key_type           = 2048

  dns_challenge {
    provider = "azuredns"
    config = {
      ARM_SUBSCRIPTION_ID = data.azurerm_client_config.current.subscription_id
      ARM_RESOURCE_GROUP  = "my-rg"
    }
  }
}
```
I'm unable to force authentication method to `cli` even with `AZURE_AUTH_METHOD` environment variable set to "cli" (at workflow step level) I get the following error: 
`* rpc error: code = Unknown desc = azure: azure.BearerAuthorizer#WithAuthorization: Failed to refresh the Token for request to https://management.azure.com/subscriptions/xxx/resourceGroups/xxx/providers/Microsoft.Network/dnsZones/xxxx?api-version=2018-05-01: StatusCode=400 -- Original Error: adal: Refresh request failed. Status Code = '400'. Response body: Failed to make request: 'Identity not found: 'ACI_MI_CLIENT_ID_xxxxxxx-xxxx-xxxx-xxxx-xxxxxxx''`

Turning off the MSI on my Azure Container Instance runner, `terraform apply` is successful

**Comment by vancluever** [comment]
Hey @sdib, unfortunately I don't use Azure so I can't really tell you how to do this or troubleshoot it, but it clearly sounds like there's some degree of conflict between what you are specifying and the MSI that you're using.

It should also be noted that I can't find `AZURE_AUTH_METHOD` on the doc page: https://registry.terraform.io/providers/vancluever/acme/latest/docs/guides/dns-providers-azuredns.

Did you try going through the troubleshooting steps documented in https://github.com/vancluever/terraform-provider-acme/blob/main/docs/lego.md?

**Comment by sdib** [comment]
Thanks @vancluever! 
Actually AZURE_AUTH_METHOD is something expected by lego's azuredns provider as per this [line](https://github.com/go-acme/lego/blob/c9ff534e393a838e79eedd6935d6c61c94a18fab/providers/dns/azuredns/azuredns.go#L34) and [here](https://go-acme.github.io/lego/dns/azuredns/#additional-configuration)

**Comment by vancluever** [comment]
@sdib looks like that hasn't been released in lego yet, we'll catch it on the next release. You could ask the lego folks to cut a new release and we will get it and update over here, otherwise it will be available when they do, which I'd image would be soon.

**Comment by vancluever** [comment]
@sdib going to close this now ahead of the release. Cheers!
