### ISSUE TITLE
Use plugin tflog for logs instead of log.Print*

### ISSUE THREAD

**Issue by Shm013** [vancluever/terraform-provider-acme#365]
I want to use variable TF_LOG_PROVIDER_ACME="DEBUG" from instruction https://developer.hashicorp.com/terraform/plugin/log/managing#testing for debugging provider TF_LOG="DEBUG" produce too much logs for me.
[tflog](https://pkg.go.dev/github.com/hashicorp/terraform-plugin-log/tflog) allow to configure log level for each provider independently without recompilation.

Can you please replace log.Print* with tflog analogs?
Terraform consider log.Print as legacy, and don't recommend to use it.
https://developer.hashicorp.com/terraform/internals/debugging

**Comment by vancluever** [comment]
@Shm013 unfortunately it looks like we're constrained by [lego's package-level logger](https://github.com/go-acme/lego/blob/7186ebb6f194c55781432162a47ff62a0bb21023/log/logger.go) here, hence we have no way of shuttling the logger context around without possibly clobbering contexts from previous resource invocations.

I don't really see a way through this that doesn't involve a massive amount of heavy lifting and workarounds that don't really seem worth it in the long run. Sorry!
