### ISSUE TITLE
DNS provider Gandiv5 access_token support 

### ISSUE THREAD

**Issue by skoop22** [vancluever/terraform-provider-acme#372]
Hi,

Gandi is transitioning to Access tokens instead of Api tokens.

Lego v0.5.0 has support for this.

https://go-acme.github.io/lego/dns/gandiv5/

**Comment by vancluever** [comment]
@skoop22 that is an extremely old version of lego, so this should be in the provider if it's supported by lego currently. Are you having issues with it?

Thanks!

**Comment by skoop22** [comment]
Well no not at this moment I created an api key.

But Gandi is deprecating use of api key's now. No idea when they will remove support for api key's.

**Comment by vancluever** [comment]
Hey folks, v2.20.0 is coming out with lego v4.15.0, so closing this now! Release should be pushed within a few hours.
