### ISSUE TITLE
Cannot use AWS_SDK_LOAD_CONFIG and AWS_PROFILE in route53 config

### ISSUE THREAD

**Issue by JohannesEbke** [vancluever/terraform-provider-acme#38]
Hi,

I've tried to use AWS_SDK_LOAD_CONFIG: "1" and AWS_PROFILE="myprofile" in the config {} section for route53, without success. I've traced it to a usage of a deprecated session.New in lego, and submitted a PR there: https://github.com/xenolf/lego/pull/528 , issue: https://github.com/xenolf/lego/issues/458

I've locally applied the patch to the vendored lego, and it fixes the issue for me.

It would be great if the fix could make it into 0.6 if possible.

Cheers,
Johannes

**Comment by vancluever** [comment]
@JohannesEbke looks like  xenolf/lego#528 got merged, so indeed that will be there when we update lego in the next release!

**Comment by vancluever** [comment]
Hey @JohannesEbke, this should be available for release v0.6.0, which should be out shortly! Keep an eye out!
