### ISSUE TITLE
Feature: Provide certificate serial number in attributes.

### ISSUE THREAD

**Issue by the-maldridge** [vancluever/terraform-provider-acme#386]
In hooking up monitoring to work out if 2 certificates are the same, its better to compare them by serial number.  Unfortunately the serial number attribute is not currently exported, so this feature request is to ask for a new attribute exporting the serial number.

**Comment by vancluever** [comment]
@the-maldridge this is done now and will be out in a future version!

**Comment by the-maldridge** [comment]
Thanks!
