### ISSUE TITLE
Feature request: add acme_server_url data source

### ISSUE THREAD

**Issue by Manbeardo** [vancluever/terraform-provider-acme#392]
Similar to how the `aws` provider has data sources that supply configuration that comes directly from the provider (e.g. `aws_default_tags`, `aws_region`), it'd be useful for the acme provider to expose its `server_url` as a data source so that modules could ensure that they use the same server url as the provider.

My specific use case: I'm using the acme provider in order to create an acme account that will be used by a kubernetes `cert-manager` issuer.  The k8s resource also needs the server url, so my less-than-ideal workaround is to plumb the server url through my terraform modules instead of pulling it from the acme provider.

**Comment by vancluever** [comment]
@Manbeardo done now!
