### ISSUE TITLE
Feature Request: Custom DNS servers

### ISSUE THREAD

**Issue by kraduk** [vancluever/terraform-provider-acme#393]
Background

It is common to order certificate in environments where split horizon DNS is implemented. ie a public version of the DNS and private view are not the same. In Azure this is implemented by private dns zones and public dns zones. A problem occurs when ordering a certificate from a DNS zone that is split horizoned, when the location from where the terraform has to be run for policy reasons is within this private dns resolution scope, as azure private dns zones do not have an NS record. The lower level acme go libraries seem to do an NS record lookup as part of its checks, and ends up in a retry loop, which ultimately gives up due to the lack of the DNS record.

Solution

Looking at the lower acme libraries it seems as though there is provision to be able to specify a custom DNS server. This hook is not exposed by the provider and would be very useful if it were. In our use case we need the private dns context to get to the terraform state via the storage accounts private endpoint. However we need a public context for the acme provider to hit the public zone.

**Comment by vancluever** [comment]
@kraduk have you read https://registry.terraform.io/providers/vancluever/acme/latest/docs/resources/certificate#about-dns-propagation-checks?

**Comment by kraduk** [comment]
How on earth did i miss that? Thankyou for you excellent provider.

**Comment by vancluever** [comment]
@kraduk no problem, glad it helped!
