### ISSUE TITLE
request to update provider version for go-acme/lego update

### ISSUE THREAD

**Issue by zbooyo** [vancluever/terraform-provider-acme#395]
Hi,
I raised a ticket for go-acme/lego: https://github.com/go-acme/lego/issues/2154
which has been fixed here: https://github.com/go-acme/lego/pull/2155/files/85d5e225baf644f96671a2725cb1d7c5b136fc11.
May I request terraform-provider-acme update to use the latest version of go-acme/lego ?

Thank you,
Marcin

**Comment by vancluever** [comment]
@zbooyo we don't update out-of-release from lego, so this will need to wait for a tagged release.

We get automatic updates here when lego releases though, so once that happens, it will be updated here!

**Comment by greenstevester** [comment]
@vancluever - is there an ETA for a v2.22.0 release to inlcude this change, which I also need?

**Comment by vancluever** [comment]
Yeah, it's been a bit now, so I've requested a tagged release in https://github.com/go-acme/lego/issues/2192.

Re-opening this so that we can track it here.

Thanks!

**Comment by vancluever** [comment]
Hey folks, release is building now and should be out in ~1hr. Cheers!
