### ISSUE TITLE
When using the provider to request a certificate we are getting "429 too many requests"

### ISSUE THREAD

**Issue by morangux** [vancluever/terraform-provider-acme#401]
When requesting a certificate we are getting  error "429 too many requests" but after a few tries we successfully getting the certificate.

Error: 429 ::POST :: https://acme.zerossl.com/v2/DV90/newAccount :: invalid character '<' looking for beginning of value :: <html>
│ <head><title>429 Too Many Requests</title></head>
│ <body>
│ <center><h1>429 Too Many Requests</h1></center>
│ <hr><center>nginx</center>
│ </body>
│ </html>
│ 
│ 
│   with module.infra.module.openshift[0].module.certificate.acme_registration.reg,
│   on .terraform/modules/infra/infra/openshift/certificate/main.tf line 9, in resource "acme_registration" "reg":
│    9: resource "acme_registration" "reg" {

This is our backend.tf
terraform {
  required_providers {
    acme = {
      source = "vancluever/acme"
      version = "2.20.2"
    }
  }
}

This is the main.tf (only the relevant part)

resource "tls_private_key" "reg_private_key" {
  algorithm = "RSA"
}

resource "acme_registration" "reg" {
  account_key_pem = tls_private_key.reg_private_key.private_key_pem
  email_address   = "test@test.com"
  external_account_binding {
    key_id      = var.key_id
    hmac_base64 = var.hmac_base64
  }
}

resource "tls_private_key" "cert_private_key" {
  algorithm = "RSA"
}

resource "tls_cert_request" "req" {
  private_key_pem = tls_private_key.cert_private_key.private_key_pem
  dns_names       = ["api.${var.cluster_name}.${var.base_domain}"]
  subject {
    common_name               = "api.${var.cluster_name}.${var.base_domain}"
  }
}

resource "acme_certificate" "certificate" {
  account_key_pem             = acme_registration.reg.account_key_pem
  common_name                 = "api.${var.cluster_name}.${var.base_domain}"
  subject_alternative_names   = ["*.apps.${var.cluster_name}.${var.base_domain}"]
  dns_challenge {
    provider = "route53"
    config = {
      AWS_HOSTED_ZONE_ID      = data.aws_route53_zone.k8.zone_id
      AWS_ACCESS_KEY_ID       = var.aws_access_key
      AWS_SECRET_ACCESS_KEY   = var.aws_secret_key
    }
  }
}

From Zero ssl support I understand that they limit the requests as follow: 
current rate limit is 7 requests per IP per second.

Can we control this number somehow? 

appreciate you help here

**Comment by vancluever** [comment]
@morangux looks like rate limits are hard-coded in lego: https://github.com/go-acme/lego/blob/f6d1413a3f81a1f17623065aa518cb2e41f6781d/certificate/authorization.go#L16

This means it will be hard for us to modify. 

7 per second seems very low though, compared to what Let's Encrypt (20). You might want to bring this up with ZeroSSL and get them to raise to be in line with LE so that they don't have issues with other integrations either.

Closing this now as we can't really deal with it here in the provider.
