### ISSUE TITLE
Improve `privateKeyFromPEM` to determine certificate type from base64 string

### ISSUE THREAD

**Issue by sbaeurle** [vancluever/terraform-provider-acme#408]
When generating a new SSL file using `openssl genrsa -out account.pem 4096` the resulting file may contain `BEGIN PRIVATE KEY` instead of `BEGIN PRIVATE RSA KEY`.

This causes https://github.com/vancluever/terraform-provider-acme/blob/e273412a6827f75301305d782e05d103d38cfe7c/acme/acme_structure.go#L323-L338 to error with the default case even though a valid private key was supplied.

To make the provider more resilient, it would be a good addition to support PKCS#8 private keys as well using `ParsePKCS8PrivateKey`

**Comment by vancluever** [comment]
Fixed in #409.
