### ISSUE TITLE
OpenTofu registry is missing GPG keys for this provider

### ISSUE THREAD

**Issue by pascal-hofmann** [vancluever/terraform-provider-acme#411]
I noticed the public GPG key of this provider is missing in the OpenTofu module registry. 

Note: For security reasons, it has to be submitted by the provider author for the OpenTofu registry to accept it.

You can follow this link to submit it: [Submit new Provider Signing Key](https://github.com/opentofu/registry/issues/new?assignees=&labels=provider-key%2Csubmission&projects=&template=provider_key.yml&title=Provider+Key%3A+)

If you don't have access to the public key anymore, it can be extracted from the terraform registry:

```
curl 'https://registry.terraform.io/v1/providers/vancluever/acme/2.22.0/download/linux/amd64' | jq --raw-output '.signing_keys | .gpg_public_keys | .[0] | .ascii_armor'
```

I attached the key for reference:
[acme_registry_key.pub.txt](https://github.com/user-attachments/files/15572874/acme_registry_key.pub.txt)

### Background
- OpenTofu is a fork of Terraform that is open-source, community-driven, and managed by the Linux Foundation.
- Hashicorp [silently changed the Terms of Service](https://github.com/opentofu/roadmap/issues/24#issuecomment-1699535216) for the terraform provider registry to disallow usage with things other than terraform, so OpenTofu had to build its own registry.

### ~~Terraform~~ OpenTofu Version
```
$ tofu --version
OpenTofu v1.7.1
on darwin_amd64
```

### Expected Behavior
Provider is downloaded and verified.

### Actual Behavior
Signature validation was skipped:
```
- Installed vancluever/acme v2.22.0. Signature validation was skipped due to the registry not containing GPG keys for this provider
```

### Steps to Reproduce
- [Install OpenTofu](https://opentofu.org/docs/intro/install/)
- Run `tofu init` in any project using this provider.

**Comment by vancluever** [comment]
@pascal-hofmann thanks! I've been holding off on OpenTofu integration work until there was some degree of interest of seeing the provider in any respective registries, but I guess they've already got the necessary metadata to grab it. I'll do the work in submitting the key in the next couple of days.

**Comment by pascal-hofmann** [comment]
Awesome, thank you (also for the great provider)!

**Comment by vancluever** [comment]
Now submitted as https://github.com/opentofu/registry/issues/640. Will close once it's accepted.

**Comment by vancluever** [comment]
Looks like we're all done here! Let me know if there's any other issues with OpenTofu.
