### ISSUE TITLE
certificate_not_after output not working

### ISSUE THREAD

**Issue by eitchugo** [vancluever/terraform-provider-acme#414]
While using the provider on the latest version as of this writing (`v2.2.0`), I couldn't see/use the attribute `certificate_not_after`, even if it appears to be on documentation and code.

For example:

```hcl
output "certificate_not_after" {
  description = "The expiry date of the certificate, laid out in RFC3339 format (2006-01-02T15:04:05Z07:00)."
  value       = acme_certificate.certificate.certificate_not_after
}
```

gives me:

```plain
│ Error: Unsupported attribute
│ 
│   on outputs.tf line 56, in output "certificate_not_after":
│   56:   value       = acme_certificate.certificate.certificate_not_after
│ 
│ This object has no argument, nested block, or exported attribute named "certificate_not_after".
```

I tried checking `acme_certificate.certificate.*` and couldn't find the `certificate_not_after` in the state raw output too. Maybe a regression?

Thank you

**Comment by vancluever** [comment]
@eitchugo I could not reproduce this using v2.23.2. This is the line I was using in my test configuration:

```
output "expiry_dates" {
  value = join(",", acme_certificate.certificates.*.certificate_not_after)
}
```

Note that I have multiple certificates in my configuration which is why I am splatting and using join. You will want to adjust for a single-certificate setup.

Thanks!
