### ISSUE TITLE
`acme_certificate` using deprecated encryption algorithm for PKCS12 certificates incompatible with OpenSSL

### ISSUE THREAD

**Issue by PGBI** [vancluever/terraform-provider-acme#426]
`acme_certificate` resource: the generated PKCS12 certificate (`certificate_p12` resource attribute) uses RC2-40-CBC encryption, which is no longer supported by OpenSSL without reverting to the "legacy" mode. The RC2-40-CBC encryption algorithm is no longer considered secured.

Can the provider be updated to use a more modern encryption algorithm accepted by OpenSSL 3 without the legacy mode?

How to reproduce:

- Create a certificate using the `acme_certificate` resource,
- copy the `certificate_p12` into a file like `/tmp/cert.pfx`,
- Run `openssl pkcs12 -in "/tmp/cert.pfx" -info -passin pass:"" -passout pass:"" -nokeys` => This will return an error.
- Run `openssl pkcs12 -in "/tmp/cert.pfx" -legacy -info -passin pass:"" -passout pass:"" -nokeys` => Passes

**Comment by vancluever** [comment]
Hey @PGBI, this is fixed in #427. Thanks!

**Comment by PGBI** [comment]
Awesome @vancluever, thanks for the quick update!
