### ISSUE TITLE
AZURE_DNS provider and AZURE_SERVICEDISCOVERY_FILTER getting azuredns: discover DNS zones: found duplicate dns zone

### ISSUE THREAD

**Issue by PbALpi7xEX** [vancluever/terraform-provider-acme#429]
Setup Azure DevOps pipeline with Terraform ...

I presumed the AZURE_SERVICEDISCOVERY_FILTER would help eliminate duplicate zones. I have some duplicate zones in my subscription but the kusto query in the AZURE_SERVICEDISCOVERY_FILTER does filter them out from what I can see in azure graph explorer query results.

The provider is throwing the following error:

[ERROR] provider.terraform-provider-acme_v2.25.0: Response contains error diagnostic: diagnostic_detail="" diagnostic_summary="error configuring plugin: rpc error: code = Unknown desc = error initializing provider: azuredns: discover DNS zones: found duplicate dns zone \"xxxxxxx\"" tf_proto_version=5.6 tf_resource_type=acme_certificate @caller=github.com/hashicorp/terraform-plugin-go@v0.23.0/tfprotov5/internal/diag/diagnostics.go:58 @module=sdk.proto 

If I delete the duplicate zones, everything works. Not sure if AZURE_SERVICEDISCOVERY_FILTER isn't working as expected, or this is expected behaviour.

**Comment by vancluever** [comment]
Hey @PbALpi7xEX sorry for the delay on this.

Unfortunately, I can't test this as I don't have an Azure account to work off of, in addition to this seemingly an issue with the DNS provider itself and nothing to do with the interaction between lego and Terraform.

Does this work under lego?

We have (brief) instructions for checking with lego and submitting an issue [here](https://github.com/vancluever/terraform-provider-acme/blob/main/docs/lego.md).

Thanks!

**Comment by vancluever** [comment]
@PbALpi7xEX going to close this as I haven't heard back from you at this point, if you still have issues feel free to respond!
