### ISSUE TITLE
DNS provider support

### ISSUE THREAD

**Issue by scriptjs** [vancluever/terraform-provider-acme#53]
Hello, does this support any other DNS providers such as DigitialOcean?

**Comment by vancluever** [comment]
@scriptjs I usually keep the DNS provider support up with that of lego. For more details, see the [documentation](https://github.com/vancluever/terraform-provider-acme/blob/master/doc/resource_acme_certificate.md#using-dns-challenges).

If you don't see a DNS provider on the list that you would like to see, please put a feature request against lego.

Thanks!

PS: DigitalOcean is a supported provider.

**Comment by scriptjs** [comment]
I seemed to have missed the section there on the providers. Many thanks for pointing this out. Btw, any chance this provider will officially land in Terraform?

**Comment by vancluever** [comment]
@scriptjs FWIW I want to add explicit docs for DNS providers as I understand that following API docs in lieu of actual docs is not the most optimal UX. And yes, this will be landing upstream eventually. Both of these events may happen in tandem. :slightly_smiling_face:

**Comment by scriptjs** [comment]
Super. This module is going to be quite helpful, thank you for creating it :) Will see how it works this week as I look to integrate it.
