### ISSUE TITLE
Plugin usage on Terraform Enterprise

### ISSUE THREAD

**Issue by maroda** [vancluever/terraform-provider-acme#57]
The problem I had attempting to use a "provider" block with versions prior to v1.0.0 is not documented. The doc does recommend version 0.6.0 if ACME v1 is needed, so it should also make a note similar to: "Omit the provider block if using version 0.6.0."

**Comment by maroda** [comment]
I didn't write the original TF module, but it uses version 0.5.0 of the Darwin plugin, and it worked fine. During troubleshooting, I recompiled to version 1.0:

>$ pwd
> /Users/matt/go/src/github.com/vancluever/terraform-provider-acme
>$ GOOS=darwin GOARCH=amd64 go build -o ./terraform-provider-acme_mac .

Now, if I use that version, I get the same 'invalid or unknown key' error. I do NOT get this error if I do nothing but replace version 1.0 binary with version 0.5.0 and do not define a provider, i.e.:

>provider "acme" {
>  server_url = "${var.letsEncryptURL}"
>}

With 0.5.0, if that is present, I will get <Error: provider.acme: : invalid or unknown key: server_url>

If that is NOT present with v0.5.0, i.e. no provider stanza exists, 'terraform plan' will run, apply, and work fine. I've seen it work in action multiple times *without* the 'provider "acme"' stanza present at all.

The moment I strongly define the provider, whether in v0.5.0 or v1.0, I get key errors. And with v1.0, if I don't define the provider, it will ask for me to provide <provider.acme.server_url>, and then will error out anyway.

**Comment by vancluever** [comment]
Hey @maroda, we are actually working on upstreaming this now, so you will be able to use the provider with Terraform directly!

The new location of the project will be [here](https://github.com/terraform-providers/terraform-provider-acme).

Thanks!
