### ISSUE TITLE
Resource to generate a PKCS #12 archive file

### ISSUE THREAD

**Issue by ebekker** [vancluever/terraform-provider-acme#60]
Currently the ACME provider's resources are accessible as PEM outputs.  It would be useful to be able to produce a PKCS #12 (PKCS12 or alternatively PFX) archive format file out of these components, as there are cases where a PFX archive is preferred or even required.

I recommend supporting this resource in a more general-purpose manner, such that you can give it an optional private key PEM, and one or more certificates (i.e. an array of certificate PEM clobs). By doing so, the resource would be usable in tandem with other resources of this provider, as well as alternate providers, such as the out-of-the-box TLS provider.

Note, I have a similar request out in [terraform-provider-tls/#29](https://github.com/terraform-providers/terraform-provider-tls/issues/29) because I do feel it is more natural and general-purpose for that provider to implement this resource, however, I'm not sure how likely the are to produce it in a timely manner.

**Comment by vancluever** [comment]
Closing out in favor of [new issue](https://github.com/terraform-providers/terraform-provider-acme/issues/2)
