### ISSUE TITLE
Publish your PGP Fingerprint

### ISSUE THREAD

**Issue by berney** [vancluever/terraform-provider-acme#61]
It is good that the releases are publish with SHA256 checksums and the checksum file is digitally signed using your PGP key. However we don't know what key should have signed the checksum file, if we knew what your keys fingerprint then we could extend trust from there.

```
> gpg --verify terraform-provider-acme_v1.0.0.SHA256SUMS.sig
gpg: assuming signed data in `terraform-provider-acme_v1.0.0.SHA256SUMS'
gpg: Signature made Mon Jun 18 06:44:16 2018 AUSEST using RSA key ID EC615CE4
gpg: Good signature from "Chris Marchesi <chrism@vancluevertech.com>"
gpg: WARNING: This key is not certified with a trusted signature!
gpg:          There is no indication that the signature belongs to the owner.
Primary key fingerprint: 245C DB0E 5171 60F3 EBC5  6923 21DA 69C2 D14B FAA8
     Subkey fingerprint: CFED 9BDD 618A FC92 C28A  3CDA 335B 84AF EC61 5CE4
```

**Comment by vancluever** [comment]
@berney sorry it wasn't obvious! My key is currently [here](https://github.com/vancluever/my-gpg-keys) (I'll get around to getting a keybase one day)!

PS: This will be a non-issue (for the most part) soon as we are working on migrating this project to be a full upstream provider.

Thanks!
