### ISSUE TITLE
digitalocean provider cert renewal is flaky

### ISSUE THREAD

**Issue by Temikus** [vancluever/terraform-provider-acme#87]
This setup used to work without issues, suddenly started misbehaving about a month ago.

Reproducible on `1.3.0`, `1.3.5` and `1.4.0`

Log on execution:
```
acme_certificate.ci: Creating...
acme_certificate.ci: Still creating... [10s elapsed]
acme_certificate.ci: Still creating... [20s elapsed]
acme_certificate.ci: Still creating... [30s elapsed]
acme_certificate.ci: Still creating... [40s elapsed]
acme_certificate.ci: Still creating... [50s elapsed]
acme_certificate.ci: Still creating... [1m0s elapsed]

Error: error creating certificate: acme: Error -> One or more domains had a problem:
[ci.mydomain.com] time limit exceeded: last error: NS ns2.digitalocean.com. did not return the expected TXT record [fqdn: _acme-challenge.ci.mydomain.com., value: 1J6yMS8zdDAtKSBmS8GNNPHw_BVuu02Wi9qcl5R5d3c]:


  on letsencrypt.tf line 14, in resource "acme_certificate" "ci":
  14: resource "acme_certificate" "ci" {
```

At the same time, while it is executing I can properly read off the challenge myself:
```
λ host -t txt _acme-challenge.ci.mydomain.com ns2.digitalocean.com
Using domain server:
Name: ns1.digitalocean.com
Address: 173.245.58.51#53
Aliases:

_acme-challenge.ci.mydomain.com descriptive text "hFZcDN0R4_Nn57faD1xrd3V0oEbwxKglMG_7K4kZxz0"
```

Gist with the debug log: https://gist.github.com/Temikus/6758fdb87ceb4ef6ff2bd061c00d80a6

I *can* get the cert renewed but it works only once every 10-20 tries. I'm not quite sure what the reason could be so any pointers would be appreciated.

Let me know if I can provide any additional info.

**Comment by vancluever** [comment]
Hey @Temikus, have you tried sending this to the lego repository yet? Also I can see that you are using the DO servers directly in your manual lookup. Is TF running on a machine that would be using those servers?

Note you can also change the DNS servers used for the propagation checks: https://www.terraform.io/docs/providers/acme/r/certificate.html#manually-specifying-recursive-nameservers-for-propagation-checks

Let us know how it goes.

**Comment by Temikus** [comment]
@vancluever Thanks for the response!
> have you tried sending this to the lego repository yet? 
No, should I try raising it with them?

> Also I can see that you are using the DO servers directly in your manual lookup. Is TF running on a machine that would be using those servers?
No, I'm just using DO DNS servers for those domains so the NS used are correct.

**Comment by vancluever** [comment]
Hey @Temikus, thanks. Yeah usually if something is up with the DNS providers it's generally a lego issue and needs to be raised with them. A good example is all of the history with the Google DNS provider.

If this is consistent you can also try tests with the lego command line tool and see if you can reproduce there as part of this, and maybe if you can't, try to determine the differences between the implementations. We generally don't wrap much around the DNS providers.

**Comment by vancluever** [comment]
This one is rather old and there doesn't seem to be anything majorly actionable here, closing now.
