### ISSUE TITLE
Duplication between common name and SANs incorrectly disallowed

### ISSUE THREAD

**Issue by jekor** [vancluever/terraform-provider-acme#90]
Error: common name X should not appear in SAN list

This prevents creating compatible certificates that contain all names in the SAN list and one of those names (arbitrarily) in the Common Name.

See https://stackoverflow.com/questions/5935369/ssl-how-do-common-names-cn-and-subject-alternative-names-san-work-together

**Comment by vancluever** [comment]
@jekor this will be allowed in v2.0.0.

Note that this is a semantic change - this is already de-duplicated on the lego side and issued certificates do contain both the CN in the SAN list in addition to the `subject_alternative_names` specified. But hopefully it should eliminate confusion on whether or not this is actually the case.
