### ISSUE TITLE
External Account Binding

### ISSUE THREAD

**Issue by Sectigo-MarcW** [vancluever/terraform-provider-acme#93]
The request is to support ‘external account binding’ as specified in RFC8555 for ACME support in Terraform. This will enable enterprise customers to obtain certificates from CAs that implement this feature at the server side as they may have an existing account with them. Popular ACME clients, e.g., Certbot, have implemented this feature already.

If interested in completing this work under contract for NRE, please contact me at marc.williams@sectigo.com.

**Comment by vancluever** [comment]
Looks like it was implemented in lego in go-acme/lego#516. This message is to just validate support in lego.

@Sectigo-MarcW I'm assuming you need the following fields added to the `acme_registration` resource?

```
   --kid value                  Key identifier from External CA. Used for External Account Binding.
   --hmac value                 MAC key from External CA. Should be in Base64 URL Encoding without padding format. Used for External Account Binding.
```

**Comment by Sectigo-MarcW** [comment]
Thank you for the fast response, Chris.  I’m going to add our Director of Product Management, Abul Salek, to the thread to confirm.

 

Best Regards,

Marc

**Comment by Sectigo-MarcW** [comment]
Yes, those are the 2 parameters we need. Lego and Certbot implemented them. 

Abul Salek
Product Management

> On Oct 25, 2019, at 2:13 PM, Marc Williams <marc.williams@sectigo.com> wrote:
> 

﻿
Thank you for the fast response, Chris.  I’m going to add our Director of Product Management, Abul Salek, to the thread to confirm.
 
Best Regards,
Marc

**Comment by vancluever** [comment]
Closing this in favor of #116.

As I don't really have a way to test this since EAB is an option generally used by paid CAs, I will need someone to test any PR I create. I'll wait until I have someone that can do this before working to implement it.
