### ISSUE TITLE
acme_certificate: add certificate expiry as an output 

### ISSUE THREAD

**Issue by dekimsey** [vancluever/terraform-provider-acme#98]
It'd be useful to be able to have acme_certificate output the acme_certificate the expiration date of the certificate. I would actually like to use this as output for another resource to publish/monitor.

Thank you!

**Comment by vancluever** [comment]
Hey @dekimsey, I don't think this is a good idea for this provider as we'd need to derive it from the certificate itself and it would produce sort of duplicate sources of truth, but you can get this and many other fields using the [`tls_certificate`](https://registry.terraform.io/providers/hashicorp/tls/latest/docs/data-sources/tls_certificate) data source.

Thanks!
