### ISSUE TITLE
Unable to import certificate as PEM into Azure Key Vault

### ISSUE THREAD

**Issue by bada09089** [vancluever/terraform-provider-acme#99]
Hello,

we currently try to import an via acme provider created certificate as PEM into azure key vault. We are already doing it with PFX but also want to be able to import it as PEM. 

If we try to import it following error appears:
"The specified PEM X.509 certificate content is in an unexpected format. Please check if certificate is in valid PEM format."

The reason seems to be that Azure expect the private key as PKCS#8 ([Azure Doc](https://docs.microsoft.com/en-us/azure/key-vault/certificate-scenarios#formats-of-import-we-support)) but the acme provider just outputs it as PKCS#1. The solution for now would be to use a local-exec to format the private key with openssl, write it into a file and afterwards read the file via data source to be able to reference it in the key vault import.

But because this solution is pretty ugly, I am trying to find another one right now. Wouldn't an additional output parameter in the acme_certificate resource for the private key as PKCS#8 be the best solution? Is there already a better/nicer way?

Below the terraform code that we are using:

	provider "acme" {
	  server_url = var.acme_provider_server_url
	}

	resource "tls_private_key" "private_key" {
	  for_each    = var.certificate
	  algorithm   = lookup(each.value, "algorithm", "RSA")
	  rsa_bits    = lookup(each.value, "rsa_bits", 4096)
	  ecdsa_curve = lookup(each.value, "ecdsa_curve", "P224")
	}

	resource "acme_registration" "registration" {
	  for_each        = var.certificate
	  account_key_pem = tls_private_key.private_key[each.key].private_key_pem
	  email_address   = each.value["email_address"]
	}

	resource "acme_certificate" "certificate" {
	  for_each                  = var.certificate
	  account_key_pem           = acme_registration.registration[each.key].account_key_pem
	  common_name               = each.key
	  subject_alternative_names = lookup(each.value, "subject_alternative_names", null) == null ? [] : split(",", lookup(each.value, "subject_alternative_names"))
	  key_type                  = lookup(each.value, "rsa_bits", 4096)
	  min_days_remaining        = lookup(each.value, "min_days_remaining", "30")
	  certificate_p12_password  = lookup(each.value, "certificate_p12_password", null)

	  dns_challenge {
		provider = lookup(each.value, "dns_challenge_provider", "azure")
		config = {
		  AZURE_CLIENT_ID       = lookup(each.value, "azure_client_id", null)
		  AZURE_CLIENT_SECRET   = lookup(each.value, "azure_client_secret", null)
		  AZURE_RESOURCE_GROUP  = lookup(each.value, "azure_resource_group", null)
		  AZURE_SUBSCRIPTION_ID = lookup(each.value, "azure_subscription_id", null)
		  AZURE_TENANT_ID       = lookup(each.value, "azure_tenant_id", null)
		}
	  }
	}

	resource "azurerm_key_vault_certificate" "key_vault_certificate" {
	  for_each     = var.key_vault_certificate == true ? var.certificate : {}
	  key_vault_id = var.key_vault_id
	  name         = replace(replace(each.key, ".", "-"), "*", "wildcard")

	  certificate {
		contents = lookup(each.value, "certificate_content_type", "application/x-pkcs12") == "application/x-pkcs12" ? acme_certificate.certificate[each.key].certificate_p12 : "${acme_certificate.certificate[each.key].certificate_pem}${acme_certificate.certificate[each.key].issuer_pem}${acme_certificate.certificate[each.key].private_key_pem}"
		password = lookup(each.value, "certificate_p12_password" , null)
	  }

	  certificate_policy {
		issuer_parameters {
		  name = lookup(each.value, "certificate_issuer", "Unknown")
		}

		key_properties {
		  exportable = true
		  key_size   = lookup(each.value, "rsa_bits", 4096)
		  key_type   = lookup(each.value, "algorithm", "RSA")
		  reuse_key  = false
		}

		secret_properties {
		  content_type = lookup(each.value, "certificate_content_type", "application/x-pkcs12")
		}
	  }
	}

Related issue: [#38](https://github.com/terraform-providers/terraform-provider-acme/issues/38#issue-421519951)
Thanks in advance!

**Comment by vancluever** [comment]
@bada09089 is this new? The PFX support was added so that the certificate could be imported into Azure.

**Comment by bada09089** [comment]
Hi @vancluever, thanks for your reply. As mentioned it's not about the PFX, we want to import it as PEM.

**Comment by vancluever** [comment]
@bada09089 sorry, I am following now.

We could probably add a `private_key_p8` field but I'm not too sure when it will be added. If you want to contribute the work, feel free to do so!

Aside from this I think the best bet for you is the OpenSSL conversion method you already mentioned.

**Comment by bada09089** [comment]
Hi @vancluever, thanks! We will stick to our solution for the time being.

**Comment by vancluever** [comment]
Hey @bada09089, sorry for the lengthy delay in addressing this.

I've had some time to look at the issue more, and I'm wondering, can Key Vault not take the PFX generated by `certificate_p12`?

The API docs seem to indicate that:

> Azure Key Vault supports .pem and .pfx certificate files for importing Certificates into Key vault.

Additionally:

> We support the following type of Import for PEM file format. A single PEM encoded certificate along with a PKCS#8 encoded, unencrypted key which has the following...

The paragraph seems to imply that the PKCS8 key is only needed when you are using a PEM versus PFX.

[There's an example in the docs](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/key_vault_certificate#example-usage-importing-a-pfx) for importing a PFX via the `azurerm_key_vault_certificate`. Have you tried that explicitly?

Additionally,

> we want to import it as PEM.

Is there a specific reason why given that the PFX bundle should contain all of the necessary information?

**Comment by vancluever** [comment]
@bada09089 as this has been waiting for a reply for a couple of weeks now I'm going to close this. If you have any feedback about the details above feel free to reply though!
